
// Lokaal account: gebruikersnaam + wachtwoordhash, profiel versleuteld met AES-GCM.
let pendingAvatar='';
function defaultAvatar(name='R'){let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" rx="55" fill="#ccfbf1"/><circle cx="100" cy="75" r="38" fill="#0f766e"/><path d="M40 180c8-47 112-47 120 0" fill="#0f766e"/><text x="100" y="190" text-anchor="middle" font-family="sans-serif" font-size="20" fill="#fff">${(name[0]||'R').toUpperCase()}</text></svg>`;return 'data:image/svg+xml;base64,'+btoa(svg)}
async function passwordHash(p,salt){let raw=await crypto.subtle.digest('SHA-256',new Uint8Array([...salt,...new TextEncoder().encode(p)]));return btoa(String.fromCharCode(...new Uint8Array(raw)))}
function currentAccount(){let u=sessionStorage.getItem('serenamindCurrent');return u?JSON.parse(localStorage.getItem('serenamindAccount:'+u)||'null'):null}
function showAccount(a){let pic=a.profile.avatar||defaultAvatar(a.profile.name);$('#headerAvatar').src=pic;$('#settingsAvatar').src=pic;$('#profileUsername').textContent='@'+a.username;state.name=a.profile.name||state.name;greet()}
async function imageData(file){return new Promise((ok,no)=>{let img=new Image(),fr=new FileReader();fr.onload=()=>img.src=fr.result;fr.onerror=no;img.onload=()=>{let max=320,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};fr.readAsDataURL(file)})}
function authTab(which){$$('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===which));$('#loginForm').classList.toggle('hidden',which!=='login');$('#registerForm').classList.toggle('hidden',which!=='register')}
addEventListener('DOMContentLoaded',()=>{$$('[data-auth]').forEach(b=>b.onclick=()=>authTab(b.dataset.auth));pendingAvatar=defaultAvatar();$('#avatarPreview').src=pendingAvatar;$('#avatarInput').onchange=async e=>{if(e.target.files[0]){if(e.target.files[0].size>5e6)return toast('Kies een foto kleiner dan 5 MB');pendingAvatar=await imageData(e.target.files[0]);$('#avatarPreview').src=pendingAvatar}};
$('#registerBtn').onclick=async()=>{let name=$('#registerName').value.trim(),user=$('#registerUser').value.trim().toLowerCase(),p=$('#registerPass').value,p2=$('#registerPass2').value;if(!name||!/^[a-z0-9._-]{3,30}$/.test(user))return toast('Vul een naam en geldige gebruikersnaam in');if(p.length<8)return toast('Wachtwoord moet minimaal 8 tekens hebben');if(p!==p2)return toast('Wachtwoorden zijn niet gelijk');if(localStorage.getItem('serenamindAccount:'+user))return toast('Deze gebruikersnaam bestaat al op dit apparaat');let salt=crypto.getRandomValues(new Uint8Array(16)),hash=await passwordHash(p,salt),account={version:1,username:user,salt:btoa(String.fromCharCode(...salt)),hash,profile:{name,avatar:pendingAvatar||defaultAvatar(name)},created:new Date().toISOString()};localStorage.setItem('serenamindAccount:'+user,JSON.stringify(account));sessionStorage.setItem('serenamindCurrent',user);$('#authScreen').classList.add('hidden');showAccount(account);toast('Welkom, '+name)};
$('#loginBtn').onclick=async()=>{let user=$('#loginUser').value.trim().toLowerCase(),p=$('#loginPass').value,a=JSON.parse(localStorage.getItem('serenamindAccount:'+user)||'null');if(!a)return toast('Account niet gevonden op dit apparaat');let salt=Uint8Array.from(atob(a.salt),c=>c.charCodeAt(0));if(await passwordHash(p,salt)!==a.hash)return toast('Onjuist wachtwoord');sessionStorage.setItem('serenamindCurrent',user);$('#authScreen').classList.add('hidden');showAccount(a);toast('Welkom terug')};
if(!window.SERENAMIND_CONFIG?.SUPABASE_URL?.startsWith('https://')){$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('serenamindCurrent');localStorage.removeItem('serenamindRemember');location.reload()};$('#headerLogoutBtn').onclick=$('#logoutBtn').onclick;$('#profileMenuBtn').onclick=()=>$('#profileMenu').classList.toggle('hidden')};$('#changePhoto').onclick=()=>$('#changePhotoInput').click();$('#changePhotoInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;let a=currentAccount();a.profile.avatar=await imageData(f);localStorage.setItem('serenamindAccount:'+a.username,JSON.stringify(a));showAccount(a);toast('Profielfoto bijgewerkt')};let a=currentAccount();if(a){$('#authScreen').classList.add('hidden');showAccount(a)}});

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={name:'',mood:3,stimuli:3,checkins:[],joy:[],tasks:[{id:'water',text:'Iets drinken',done:false},{id:'food',text:'Iets voedzaams eten',done:false},{id:'light',text:'5 minuten daglicht',done:false},{id:'pause',text:'Een prikkelarme pauze',done:false}],gratitude:{},prefs:{dark:false,quiet:false,large:false,contrast:false},support:{name:'',phone:''}};
let state={...defaults,...JSON.parse(localStorage.getItem('serenamindPlus')||'{}')}; let unlockedEntries=null, journalKey=null, selectedEmotion='';
const save=()=>localStorage.setItem('serenamindPlus',JSON.stringify(state));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));scrollTo(0,0);if(id==='insights')renderInsights();if(id==='journal')updateJournalLock()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
const daily=['Een kleine stap is nog steeds een stap.','Rust nemen is ook voor jezelf zorgen.','Je hoeft dit moment niet meteen op te lossen.','Vandaag mag zacht en eenvoudig zijn.'];$('#dailyText').textContent=daily[new Date().getDate()%daily.length];
const moodNames=['heel zwaar','zwaar','neutraal','redelijk','licht'];function labels(){$('#moodLabel').textContent=moodNames[$('#mood').value-1];$('#stimuliLabel').textContent=$('#stimuli').value+'/5';suggest()}$('#mood').value=state.mood;$('#stimuli').value=state.stimuli;$('#mood').oninput=labels;$('#stimuli').oninput=labels;
const suggestions={high:['Dim je scherm en zet meldingen 10 minuten uit.','Ga, als dat veilig is, naar een stillere plek.','Kies één zintuiglijk rustig ding: deken, water of stilte.'],low:['Neem een paar slokken water.','Kies één taak die minder dan twee minuten duurt.','Laat iets niet-noodzakelijks vandaag los.'],ok:['Plan na je volgende taak vijf minuten herstel.','Stuur iemand die je vertrouwt een kort bericht.','Kies één prettig ding voor later vandaag.']};function suggest(){let type=Number($('#stimuli').value)>=4?'high':Number($('#mood').value)<=2?'low':'ok';let a=suggestions[type];$('#suggestion').textContent=a[Math.floor(Math.random()*a.length)]}$('#newSuggestion').onclick=suggest;labels();
$('#saveCheckin').onclick=()=>{state.mood=Number($('#mood').value);state.stimuli=Number($('#stimuli').value);state.checkins.push({at:new Date().toISOString(),mood:state.mood,stimuli:state.stimuli});state.checkins=state.checkins.slice(-90);save();toast('Check-in lokaal bewaard')};
// Calm tools
$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.toolpanel').forEach(p=>p.classList.add('hidden'));$('#'+b.dataset.tool+'Panel').classList.remove('hidden')});
let breathTimer,breathLeft=0,inhale=true;$('#breathBtn').onclick=()=>{if(breathTimer){clearInterval(breathTimer);breathTimer=null;$('#breathBtn').textContent='Start';$('#breathText').textContent='Gepauzeerd';return}breathLeft=Number($('#breathLength').value);$('#breathBtn').textContent='Stop';breathTimer=setInterval(()=>{breathLeft--;if(breathLeft<=0){clearInterval(breathTimer);breathTimer=null;$('#breathText').textContent='Klaar. Neem rustig de tijd.';$('#breathBtn').textContent='Start';$('#orb').style.transform='scale(1)';return}if(breathLeft%4===0){inhale=!inhale;$('#orb').style.transform=inhale?'scale(1.16)':'scale(.86)'}$('#breathText').textContent=(inhale?'Adem comfortabel in':'Adem rustig uit')+' · '+breathLeft+' sec'},1000)};
const senses=[['5','dingen die je ziet'],['4','dingen die je voelt'],['3','geluiden die je hoort'],['2','geuren die je opmerkt'],['1','smaak of helpende gedachte']];let senseIndex=0;function renderSense(){[$('#senseN').textContent,$('#senseText').textContent]=senses[senseIndex]}$('#senseNext').onclick=()=>{senseIndex=(senseIndex+1)%5;renderSense()};$('#senseBack').onclick=()=>{senseIndex=Math.max(0,senseIndex-1);renderSense()};
let pauseInt;$$('[data-pause]').forEach(b=>b.onclick=()=>{clearInterval(pauseInt);let left=Number(b.dataset.pause);pauseInt=setInterval(()=>{left--;let m=Math.floor(left/60),s=left%60;$('#pauseTimer').textContent=`${m}:${String(s).padStart(2,'0')}`;if(left<=0){clearInterval(pauseInt);$('#pauseTimer').textContent='Pauze afgerond ✓'}},1000)});
const releases=['Laat je schouders een klein beetje zakken.','Ontspan je kaken zonder te forceren.','Voel waar je lichaam wordt ondersteund.','Maak je handen zacht en open.','Kijk naar een vast, rustig punt in de ruimte.'];let ri=0;$('#releaseNext').onclick=()=>{$('#releaseText').textContent=releases[++ri%releases.length]};
// Cheer
const cheers=[['🌤️','Een zachte herinnering','Je hoeft je niet meteen beter te voelen. Een klein prettig moment telt ook.'],['🌱','Groei hoeft niet snel','Ook rust, grenzen en opnieuw proberen zijn vormen van groei.'],['🫖','Maak het klein','Een warme drank, frisse lucht of fijn lied kan genoeg zijn voor dit moment.'],['💛','Je bent meer dan vandaag','Een moeilijke dag zegt niet alles over wie jij bent.'],['✨','Kijk naar wat lukte','Misschien ben je opgestaan, heb je dit geopend of om hulp gevraagd. Dat telt.']];function cheer(){let c=cheers[Math.floor(Math.random()*cheers.length)];[$('#cheerEmoji').textContent,$('#cheerTitle').textContent,$('#cheerText').textContent]=c}$('#anotherCheer').onclick=cheer;
const activities=['warme thee','kort naar buiten','favoriete muziek','warme douche','deken en rust','iets tekenen','iemand appen','grappig filmpje'];$('#activityChips').innerHTML=activities.map(x=>`<button>${x}</button>`).join('');$('#activityChips').onclick=e=>{if(e.target.tagName==='BUTTON'){$('#joyInput').value=e.target.textContent}};
function renderJoy(){$('#joyList').innerHTML=state.joy.length?state.joy.map((x,i)=>`<div><button data-deljoy="${i}">×</button>♡ ${escapeHtml(x)}</div>`).join(''):'<p class="fine">Voeg dingen toe die jou soms een klein prettig gevoel geven.</p>'}$('#addJoy').onclick=()=>{let v=$('#joyInput').value.trim();if(!v)return;state.joy.push(v);$('#joyInput').value='';save();renderJoy()};$('#joyList').onclick=e=>{if(e.target.dataset.deljoy!==undefined){state.joy.splice(Number(e.target.dataset.deljoy),1);save();renderJoy()}};renderJoy();
// Tasks
function renderTasks(){$('#taskList').innerHTML=state.tasks.map(t=>`<button class="task ${t.done?'done':''}" data-task="${t.id}">${t.done?'✓':'○'} <span>${escapeHtml(t.text)}</span></button>`).join('')}$('#taskList').onclick=e=>{let b=e.target.closest('[data-task]');if(!b)return;let t=state.tasks.find(x=>x.id===b.dataset.task);t.done=!t.done;save();renderTasks()};$('#addTask').onclick=()=>{let v=$('#taskInput').value.trim();if(!v)return;state.tasks.push({id:crypto.randomUUID(),text:v,done:false});$('#taskInput').value='';save();renderTasks()};$('#resetTasks').onclick=()=>{state.tasks=state.tasks.map(t=>({...t,done:false}));save();renderTasks()};renderTasks();let today=()=>new Date().toISOString().slice(0,10);$('#gratitude').value=state.gratitude[today()]||'';$('#saveGratitude').onclick=()=>{state.gratitude[today()]=$('#gratitude').value;save();toast('Lichtpuntje bewaard')};
// Journal crypto: PBKDF2 + AES-GCM
const enc=new TextEncoder(),dec=new TextDecoder();const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt){let base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptJournal(entries,key){let iv=crypto.getRandomValues(new Uint8Array(12));let data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(entries)));return {iv:b64(iv),data:b64(data)}}
async function decryptJournal(blob,key){let data=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(blob.iv)},key,unb64(blob.data));return JSON.parse(dec.decode(data))}
function updateJournalLock(){let exists=!!localStorage.getItem('serenamindJournal');$('#lockTitle').textContent=exists?'Ontgrendel je dagboek':'Maak een dagboekwachtwoord';$('#lockHelp').textContent=exists?'Voer je eigen wachtwoord in.':'Je notities worden versleuteld op dit apparaat. Kies minimaal 8 tekens.'}
$('#unlockJournal').onclick=async()=>{let p=$('#journalPassword').value;if(p.length<8){toast('Gebruik minimaal 8 tekens');return}try{let saved=JSON.parse(localStorage.getItem('serenamindJournal')||'null');let salt=saved?unb64(saved.salt):crypto.getRandomValues(new Uint8Array(16));let key=await derive(p,salt);let entries=saved?await decryptJournal(saved,key):[];journalKey=key;unlockedEntries=entries;if(!saved){let blob=await encryptJournal([],key);localStorage.setItem('serenamindJournal',JSON.stringify({salt:b64(salt),...blob}))}$('#journalPassword').value='';$('#journalLocked').classList.add('hidden');$('#journalOpen').classList.remove('hidden');renderEntries();toast('Dagboek ontgrendeld')}catch(e){toast('Wachtwoord klopt niet of gegevens zijn beschadigd')}};
async function persistJournal(){let saved=JSON.parse(localStorage.getItem('serenamindJournal'));let blob=await encryptJournal(unlockedEntries,journalKey);localStorage.setItem('serenamindJournal',JSON.stringify({salt:saved.salt,...blob}))}
$$('.moodchips button').forEach(b=>b.onclick=()=>{$$('.moodchips button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedEmotion=b.dataset.emotion});
$('#saveEntry').onclick=async()=>{let text=$('#entryText').value.trim();if(!text)return toast('Schrijf eerst iets');unlockedEntries.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),title:$('#entryTitle').value.trim()||'Zonder titel',text,emotion:selectedEmotion});await persistJournal();$('#entryTitle').value='';$('#entryText').value='';selectedEmotion='';$$('.moodchips button').forEach(x=>x.classList.remove('selected'));renderEntries();toast('Notitie versleuteld bewaard')};
function renderEntries(){if(!unlockedEntries)return;let q=$('#searchEntries').value.toLowerCase();let list=unlockedEntries.filter(e=>(e.title+' '+e.text+' '+e.emotion).toLowerCase().includes(q));$('#entryList').innerHTML=list.length?list.map(e=>`<article><button data-entrydel="${e.id}">×</button><h4>${escapeHtml(e.title)}</h4><small>${new Date(e.at).toLocaleString('nl-NL')} ${e.emotion?'· '+escapeHtml(e.emotion):''}</small><p>${escapeHtml(e.text).replace(/\n/g,'<br>')}</p></article>`).join(''):'<p class="fine">Geen notities gevonden.</p>'}$('#searchEntries').oninput=renderEntries;$('#entryList').onclick=async e=>{if(e.target.dataset.entrydel){if(confirm('Deze notitie definitief verwijderen?')){unlockedEntries=unlockedEntries.filter(x=>x.id!==e.target.dataset.entrydel);await persistJournal();renderEntries()}}};
$('#lockJournal').onclick=()=>{unlockedEntries=null;journalKey=null;$('#journalOpen').classList.add('hidden');$('#journalLocked').classList.remove('hidden');toast('Dagboek vergrendeld')};$('#deleteJournal').onclick=()=>{if(confirm('Het volledige versleutelde dagboek verwijderen? Dit kan niet ongedaan worden.')){localStorage.removeItem('serenamindJournal');unlockedEntries=null;journalKey=null;$('#journalOpen').classList.add('hidden');$('#journalLocked').classList.remove('hidden');updateJournalLock()}};
$('#exportJournal').onclick=()=>{let raw=localStorage.getItem('serenamindJournal');download('serenamind-dagboek-versleuteld.json',raw)};
// Insights and export
function renderInsights(){let a=state.checkins.slice(-7);$('#checkinCount').textContent=state.checkins.length;$('#avgMood').textContent=a.length?(a.reduce((s,x)=>s+x.mood,0)/a.length).toFixed(1):'–';$('#avgStimuli').textContent=a.length?(a.reduce((s,x)=>s+x.stimuli,0)/a.length).toFixed(1):'–';$('#bars').innerHTML=a.length?a.map(x=>`<div class="bar" title="Gevoel ${x.mood}, prikkels ${x.stimuli}"><i class="m" style="height:${x.mood*20}%"></i><i class="s" style="height:${x.stimuli*20}%"></i></div>`).join(''):'<p class="fine">Nog geen check-ins.</p>'}$('#exportAll').onclick=()=>download('serenamind-instellingen.json',JSON.stringify(state,null,2));
// Settings
function applyPrefs(){document.body.classList.toggle('dark',state.prefs.dark);document.body.classList.toggle('quiet',state.prefs.quiet);document.body.classList.toggle('large',state.prefs.large);document.body.classList.toggle('contrast',state.prefs.contrast);$('#darkMode').checked=state.prefs.dark;$('#quietMode').checked=state.prefs.quiet;$('#largeText').checked=state.prefs.large;$('#highContrast').checked=state.prefs.contrast}['dark','quiet','large','contrast'].forEach((k,i)=>{let ids=['darkMode','quietMode','largeText','highContrast'];$('#'+ids[i]).onchange=e=>{state.prefs[k]=e.target.checked;save();applyPrefs()}});$('#quietBtn').onclick=()=>{state.prefs.quiet=!state.prefs.quiet;save();applyPrefs()};applyPrefs();
$('#displayName').value=state.name||'';function greet(){$('#greeting').textContent=state.name?`Fijn dat je er bent, ${state.name}`:'Fijn dat je er bent'}greet();$('#saveName').onclick=()=>{state.name=$('#displayName').value.trim();save();greet();toast('Naam bewaard')};$('#supportName').value=state.support.name||'';$('#supportPhone').value=state.support.phone||'';function support(){if(state.support.phone){$('#supportCall').classList.remove('hidden');$('#supportCall').href='tel:'+state.support.phone;$('#supportCall').textContent='Bel '+(state.support.name||'mijn steuncontact')}}support();$('#saveSupport').onclick=()=>{state.support={name:$('#supportName').value.trim(),phone:$('#supportPhone').value.trim()};save();support();toast('Steuncontact lokaal bewaard')};
$('#setReminder').onclick=async()=>{if(!('Notification'in window))return toast('Meldingen worden niet ondersteund');let p=await Notification.requestPermission();if(p!=='granted')return toast('Geen toestemming voor meldingen');localStorage.setItem('serenamindReminder',$('#reminderTime').value);toast('Tijd bewaard. Houd er rekening mee dat webbrowsers geen garantie bieden wanneer de app gesloten is.');if($('#reminderTime').value)new Notification('SerenaMind',{body:'Je dagelijkse herinnering staat klaar.'})};$('#reminderTime').value=localStorage.getItem('serenamindReminder')||'';
$('#clearGeneral').onclick=()=>{if(confirm('Alle niet-dagboekgegevens wissen?')){localStorage.removeItem('serenamindPlus');location.reload()}};
// Crisis
$('#crisisBtn').onclick=()=>$('#crisisModal').classList.add('show');$('#closeCrisis').onclick=()=>$('#crisisModal').classList.remove('show');
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
updateJournalLock();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));


// Communication center
const commFields=['commObservation','commFeeling','commNeed','commRequest'];
function buildMessage(){let [o,f,n,q]=commFields.map(id=>$('#'+id).value.trim()),parts=[];if(o)parts.push(o);if(f)parts.push('Ik merk dat '+f.charAt(0).toLowerCase()+f.slice(1));if(n)parts.push('Wat mij helpt is '+n.charAt(0).toLowerCase()+n.slice(1));if(q)parts.push(q);let msg=parts.join('. ').replace(/\.\./g,'.');if(msg&&!/[.!?]$/.test(msg))msg+='.';$('#commPreview').textContent=msg||'Vul één of meer velden in.';return msg}commFields.forEach(id=>$('#'+id).oninput=buildMessage);
const templates=['Ik wil graag reageren, maar ik heb eerst wat tijd nodig om mijn gedachten te ordenen.','Er komt nu veel tegelijk binnen. Kunnen we dit in kleine stappen bespreken?','Ik hoor wat je zegt. Ik heb behoefte aan een korte pauze en kom hier later op terug.','Kun je de belangrijkste afspraak ook schriftelijk sturen? Dat helpt mij om overzicht te houden.','Ik kan dit vandaag niet goed verwerken. Kunnen we een rustiger moment plannen?','Ik wil graag helpen, maar ik moet eerst controleren hoeveel ruimte ik vandaag heb.'];
$('#templateList').innerHTML=templates.map((t,i)=>`<button data-template="${i}">${escapeHtml(t)}</button>`).join('');$('#templateList').onclick=e=>{let b=e.target.closest('[data-template]');if(!b)return;$('#commRequest').value=templates[Number(b.dataset.template)];buildMessage();toast('Voorbeeld in de berichtenbouwer gezet')};
$('#copyMessage').onclick=async()=>{let m=buildMessage();if(!m)return toast('Vul eerst een bericht in');await navigator.clipboard.writeText(m);toast('Bericht gekopieerd')};$('#shareMessage').onclick=async()=>{let m=buildMessage();if(!m)return toast('Vul eerst een bericht in');if(navigator.share)await navigator.share({title:'SerenaMind bericht',text:m});else{await navigator.clipboard.writeText(m);toast('Delen niet beschikbaar; bericht gekopieerd')}};
$('#meetingNotes').value=localStorage.getItem('serenamindMeetingNotes')||'';$('#saveMeetingNotes').onclick=()=>{localStorage.setItem('serenamindMeetingNotes',$('#meetingNotes').value);toast('Gesprekspunten lokaal bewaard')};let commInt;$('#startCommPause').onclick=()=>{clearInterval(commInt);let n=60;$('#commTimer').textContent='1:00';commInt=setInterval(()=>{n--;$('#commTimer').textContent='0:'+String(n).padStart(2,'0');if(n<=0){clearInterval(commInt);$('#commTimer').textContent='Je kunt nu rustig opnieuw lezen.'}},1000)};

// Advanced tasks and native local reminders
state.todos=state.todos||[];
function localDate(){let d=new Date(),off=d.getTimezoneOffset();return new Date(d-off*60000).toISOString().slice(0,10)}
$('#todoDate').value=localDate();
function todoNotifId(id){let h=0;for(let c of id)h=(h*31+c.charCodeAt(0))|0;return Math.abs(h)%2000000000+1}
async function notificationApi(){try{return await import('@capacitor/local-notifications')}catch(e){return null}}
async function scheduleTodo(t){if(!t.reminder||!t.date||!t.time)return;let when=new Date(t.date+'T'+t.time);if(when<=new Date())return toast('Kies een tijd in de toekomst');let mod=await notificationApi();if(mod?.LocalNotifications){let perm=await mod.LocalNotifications.requestPermissions();if(perm.display!=='granted')return toast('Geen toestemming voor meldingen');await mod.LocalNotifications.schedule({notifications:[{id:todoNotifId(t.id),title:'SerenaMind herinnering',body:t.title,schedule:t.repeat?{at:when,repeats:true,every:'day'}:{at:when},extra:{todoId:t.id}}]});toast('Taak en telefoonherinnering gepland')}else if('Notification'in window){let p=await Notification.requestPermission();if(p==='granted'){let delay=when-Date.now();if(delay<2147483647)setTimeout(()=>new Notification('SerenaMind herinnering',{body:t.title}),delay);toast('Browserherinnering gepland zolang de app actief blijft')}}}
async function cancelTodoReminder(t){let mod=await notificationApi();if(mod?.LocalNotifications)await mod.LocalNotifications.cancel({notifications:[{id:todoNotifId(t.id)}]})}
function renderTodos(){let filter=$('#todoFilter').value,today=localDate(),items=state.todos.filter(t=>filter==='all'||filter==='done'&&t.done||filter==='open'&&!t.done||filter==='today'&&t.date===today);items.sort((a,b)=>(a.done-b.done)||((a.date||'9999')+(a.time||'')).localeCompare((b.date||'9999')+(b.time||'')));$('#todoList').innerHTML=items.length?items.map(t=>`<article class="todoItem ${t.done?'done':''} priority-${t.priority}"><div class="todoTop"><input type="checkbox" data-checktodo="${t.id}" ${t.done?'checked':''}><div class="todoBody"><b>${escapeHtml(t.title)}</b>${t.notes?`<span>${escapeHtml(t.notes)}</span>`:''}<div class="todoMeta">${t.date||'Geen datum'} ${t.time||''} · ${t.priority==='high'?'Belangrijk':t.priority==='low'?'Rustig':'Normaal'} ${t.reminder?'· 🔔':''} ${t.repeat?'· dagelijks':''}</div></div></div><div class="todoActions"><button data-snooze="${t.id}">+10 min</button><button data-deltodo="${t.id}">Verwijder</button></div></article>`).join(''):'<p class="fine">Geen taken in deze weergave.</p>';$('#taskOpenCount').textContent=state.todos.filter(t=>!t.done).length;$('#taskTodayCount').textContent=state.todos.filter(t=>!t.done&&t.date===today).length;$('#taskDoneCount').textContent=state.todos.filter(t=>t.done).length}
$('#addTodo').onclick=async()=>{let title=$('#todoTitle').value.trim();if(!title)return toast('Vul een taak in');let t={id:crypto.randomUUID(),title,notes:$('#todoNotes').value.trim(),date:$('#todoDate').value,time:$('#todoTime').value,priority:$('#todoPriority').value,reminder:$('#todoReminder').checked,repeat:$('#todoRepeat').checked,done:false,created:new Date().toISOString()};state.todos.push(t);save();renderTodos();$('#todoTitle').value='';$('#todoNotes').value='';await scheduleTodo(t)};$('#todoFilter').onchange=renderTodos;
$('#todoList').onclick=async e=>{let id=e.target.dataset.checktodo||e.target.dataset.deltodo||e.target.dataset.snooze;if(!id)return;let t=state.todos.find(x=>x.id===id);if(e.target.dataset.checktodo){t.done=e.target.checked;if(t.done)await cancelTodoReminder(t)}else if(e.target.dataset.deltodo){await cancelTodoReminder(t);state.todos=state.todos.filter(x=>x.id!==id)}else{let d=new Date(Date.now()+10*60000);t.date=new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);t.time=d.toTimeString().slice(0,5);t.done=false;t.reminder=true;await cancelTodoReminder(t);await scheduleTodo(t)}save();renderTodos()};$('#clearDoneTodos').onclick=()=>{state.todos=state.todos.filter(t=>!t.done);save();renderTodos()};
$('#testNotification').onclick=async()=>{let t={id:crypto.randomUUID(),title:'Je SerenaMind-melding werkt ✓',date:localDate(),time:'',reminder:true};let d=new Date(Date.now()+10000),mod=await notificationApi();if(mod?.LocalNotifications){let perm=await mod.LocalNotifications.requestPermissions();if(perm.display==='granted'){await mod.LocalNotifications.schedule({notifications:[{id:todoNotifId(t.id),title:'SerenaMind',body:t.title,schedule:{at:d}}]});toast('Testmelding komt over 10 seconden')}}else if('Notification'in window){let p=await Notification.requestPermission();if(p==='granted'){setTimeout(()=>new Notification('SerenaMind',{body:t.title}),10000);toast('Houd de app 10 seconden open')}}};renderTodos();
