
// Lokaal account: gebruikersnaam + wachtwoordhash, profiel versleuteld met AES-GCM.
let pendingAvatar='';
function defaultAvatar(name='R'){let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" rx="55" fill="#ccfbf1"/><circle cx="100" cy="75" r="38" fill="#0f766e"/><path d="M40 180c8-47 112-47 120 0" fill="#0f766e"/><text x="100" y="190" text-anchor="middle" font-family="sans-serif" font-size="20" fill="#fff">${(name[0]||'R').toUpperCase()}</text></svg>`;return 'data:image/svg+xml;base64,'+btoa(svg)}
async function passwordHash(p,salt){let raw=await crypto.subtle.digest('SHA-256',new Uint8Array([...salt,...new TextEncoder().encode(p)]));return btoa(String.fromCharCode(...new Uint8Array(raw)))}
function currentAccount(){let u=sessionStorage.getItem('rustpuntCurrent');return u?JSON.parse(localStorage.getItem('rustpuntAccount:'+u)||'null'):null}
function showAccount(a){let pic=a.profile.avatar||defaultAvatar(a.profile.name);$('#headerAvatar').src=pic;$('#settingsAvatar').src=pic;$('#profileUsername').textContent='@'+a.username;state.name=a.profile.name||state.name;greet()}
async function imageData(file){return new Promise((ok,no)=>{let img=new Image(),fr=new FileReader();fr.onload=()=>img.src=fr.result;fr.onerror=no;img.onload=()=>{let max=320,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};fr.readAsDataURL(file)})}
function authTab(which){$$('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===which));$('#loginForm').classList.toggle('hidden',which!=='login');$('#registerForm').classList.toggle('hidden',which!=='register')}
addEventListener('DOMContentLoaded',()=>{$$('[data-auth]').forEach(b=>b.onclick=()=>authTab(b.dataset.auth));pendingAvatar=defaultAvatar();$('#avatarPreview').src=pendingAvatar;$('#avatarInput').onchange=async e=>{if(e.target.files[0]){if(e.target.files[0].size>5e6)return toast('Kies een foto kleiner dan 5 MB');pendingAvatar=await imageData(e.target.files[0]);$('#avatarPreview').src=pendingAvatar}};
$('#registerBtn').onclick=async()=>{let name=$('#registerName').value.trim(),user=$('#registerUser').value.trim().toLowerCase(),p=$('#registerPass').value,p2=$('#registerPass2').value;if(!name||!/^[a-z0-9._-]{3,30}$/.test(user))return toast('Vul een naam en geldige gebruikersnaam in');if(p.length<8)return toast('Wachtwoord moet minimaal 8 tekens hebben');if(p!==p2)return toast('Wachtwoorden zijn niet gelijk');if(localStorage.getItem('rustpuntAccount:'+user))return toast('Deze gebruikersnaam bestaat al op dit apparaat');let salt=crypto.getRandomValues(new Uint8Array(16)),hash=await passwordHash(p,salt),account={version:1,username:user,salt:btoa(String.fromCharCode(...salt)),hash,profile:{name,avatar:pendingAvatar||defaultAvatar(name)},created:new Date().toISOString()};localStorage.setItem('rustpuntAccount:'+user,JSON.stringify(account));sessionStorage.setItem('rustpuntCurrent',user);$('#authScreen').classList.add('hidden');showAccount(account);toast('Welkom, '+name)};
$('#loginBtn').onclick=async()=>{let user=$('#loginUser').value.trim().toLowerCase(),p=$('#loginPass').value,a=JSON.parse(localStorage.getItem('rustpuntAccount:'+user)||'null');if(!a)return toast('Account niet gevonden op dit apparaat');let salt=Uint8Array.from(atob(a.salt),c=>c.charCodeAt(0));if(await passwordHash(p,salt)!==a.hash)return toast('Onjuist wachtwoord');sessionStorage.setItem('rustpuntCurrent',user);$('#authScreen').classList.add('hidden');showAccount(a);toast('Welkom terug')};
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('rustpuntCurrent');location.reload()};$('#changePhoto').onclick=()=>$('#changePhotoInput').click();$('#changePhotoInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;let a=currentAccount();a.profile.avatar=await imageData(f);localStorage.setItem('rustpuntAccount:'+a.username,JSON.stringify(a));showAccount(a);toast('Profielfoto bijgewerkt')};let a=currentAccount();if(a){$('#authScreen').classList.add('hidden');showAccount(a)}});

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={name:'',mood:3,stimuli:3,checkins:[],joy:[],tasks:[{id:'water',text:'Iets drinken',done:false},{id:'food',text:'Iets voedzaams eten',done:false},{id:'light',text:'5 minuten daglicht',done:false},{id:'pause',text:'Een prikkelarme pauze',done:false}],gratitude:{},prefs:{dark:false,quiet:false,large:false,contrast:false},support:{name:'',phone:''}};
let state={...defaults,...JSON.parse(localStorage.getItem('rustpuntPlus')||'{}')}; let unlockedEntries=null, journalKey=null, selectedEmotion='';
const save=()=>localStorage.setItem('rustpuntPlus',JSON.stringify(state));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));scrollTo(0,0);if(id==='insights')renderInsights();if(id==='journal')updateJournalLock()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
const daily=['Een kleine stap is nog steeds een stap.','Rust nemen is ook voor jezelf zorgen.','Je hoeft dit moment niet meteen op te lossen.','Vandaag mag zacht en eenvoudig zijn.'];$('#dailyText').textContent=daily[new Date().getDate()%daily.length];
const moodNames=['heel zwaar','zwaar','neutraal','redelijk','licht'];function labels(){$('#moodLabel').textContent=moodNames[$('#mood').value-1];$('#stimuliLabel').textContent=$('#stimuli').value+'/5';suggest()}$('#mood').value=state.mood;$('#stimuli').value=state.stimuli;$('#mood').oninput=labels;$('#stimuli').oninput=labels;
const suggestions={high:['Dim je scherm en zet meldingen 10 minuten uit.','Ga, als dat veilig is, naar een stillere plek.','Kies één zintuiglijk rustig ding: deken, water of stilte.'],low:['Neem een paar slokken water.','Kies één taak die minder dan twee minuten duurt.','Laat iets niet-noodzakelijks vandaag los.'],ok:['Plan na je volgende taak vijf minuten herstel.','Stuur iemand die je vertrouwt een kort bericht.','Kies één prettig ding voor later vandaag.']};function suggest(){let type=Number($('#stimuli').value)>=4?'high':Number($('#mood').value)<=2?'low':'ok';let a=suggestions[type];$('#suggestion').textContent=a[Math.floor(Math.random()*a.length)]}$('#newSuggestion').onclick=suggest;labels();
$('#saveCheckin').onclick=()=>{state.mood=Number($('#mood').value);state.stimuli=Number($('#stimuli').value);state.checkins.push({at:new Date().toISOString(),mood:state.mood,stimuli:state.stimuli});state.checkins=state.checkins.slice(-90);save();toast('Check-in lokaal bewaard')};
// Calm tools
$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.toolpanel').forEach(p=>p.classList.add('hidden'));$('#'+b.dataset.tool+'Panel').classList.remove('hidden')});
let breathTimer,breathLeft=0,inhale=true;$('#breathBtn').onclick=()=>{if(breathTimer){clearInterval(breathTimer);breathTimer=null;$('#breathBtn').textContent='Start';$('#breathText').textContent='Gepauzeerd';return}breathLeft=Number($('#breathLength').value);$('#breathBtn').textContent='Stop';breathTimer=setInterval(()=>{breathLeft--;if(breathLeft<=0){clearInterval(breathTimer);breathTimer=null;$('#breathText').textContent='Klaar. Neem rustig de tijd.';$('#breathBtn').textContent='Start';$('#orb').style.transform='scale(1)';return}if(breathLeft%4===0){inhale=!inhale;$('#orb').style.transform=inhale?'scale(1.16)':'scale(.86)'}$('#breathText').textContent=(inhale?'Adem comfortabel in':'Adem rustig uit')+' · '+breathLeft+' sec'},1000)};
const senses=[['5','dingen die je ziet'],['4','dingen die je voelt'],['3','geluiden die je hoort'],['2','geuren die je opmerkt'],['1','smaak of helpende gedachte']];let senseIndex=0;function renderSense(){[$('#senseN').textContent,$('#senseText').textContent]=senses[senseIndex]}$('#senseNext').onclick=()=>{senseIndex=(senseIndex+1)%5;renderSense()};$('#senseBack').onclick=()=>{senseIndex=Math.max(0,senseIndex-1);renderSense()};
let pauseInt;$$('[data-pause]').forEach(b=>b.onclick=()=>{clearInterval(pauseInt);let left=Number(b.dataset.pause);pauseInt=setInterval(()=>{left--;let m=Math.floor(left/60),s=left%60;$('#pauseTimer').textContent=`${m}:${String(s).padStart(2,'0')}`;if(left<=0){clearInterval(pauseInt);$('#pauseTimer').textContent='Pauze afgerond ✓'}},1000)});
const releases=['Laat je schouders een klein beetje zakken.','Ontspan je kaken zonder te forceren.','Voel waar je lichaam wordt ondersteund.','Maak je handen zacht en open.','Kijk naar een vast, rustig punt in de ruimte.'];let ri=0;$('#releaseNext').onclick=()=>{$('#releaseText').textContent=releases[++ri%releases.length]};
// Cheer
const cheers=[['🌤️','Een zachte herinnering','Je hoeft je niet meteen beter te voelen. Een klein prettig moment telt ook.'],['🌱','Groei hoeft niet snel','Ook rust, grenzen en opnieuw proberen zijn vormen van groei.'],['🫖','Maak het klein','Een warme drank, frisse lucht of fijn lied kan genoeg zijn voor dit moment.'],['💛','Je bent meer dan vandaag','Een moeilijke dag zegt niet alles over wie jij bent.'],['✨','Kijk naar wat lukte','Misschien ben je opgestaan, heb je dit geopend of om hulp gevraagd. Dat telt.']];function cheer(){let c=cheers[Math.floor(Math.random()*cheers.length)];[$('#cheerEmoji').textContent,$('#cheerTitle').textContent,$('#cheerText').textContent]=c}$('#anotherCheer').onclick=cheer;
const activities=['warme thee','kort naar buiten','favoriete muziek','warme douche','deken en rust','iets tekenen','iemand appen','grappig filmpje'];$('#activityChips').innerHTML=activities.map(x=>`<button>${x}</button>`).join('');$('#activityChips').onclick=e=>{if(e.target.tagName==='BUTTON'){$('#joyInput').value=e.target.textContent}};
function renderJoy(){$('#joyList').innerHTML=state.joy.length?state.joy.map((x,i)=>`<div><button data-deljoy="${i}">×</button>♡ ${escapeHtml(x)}</div>`).join(''):'<p class="fine">Voeg dingen toe die jou soms een klein prettig gevoel geven.</p>'}$('#addJoy').onclick=()=>{let v=$('#joyInput').value.trim();if(!v)return;state.joy.push(v);$('#joyInput').value='';save();renderJoy()};$('#joyList').onclick=e=>{if(e.target.dataset.deljoy!==undefined){state.joy.splice(Number(e.target.dataset.deljoy),1);save();renderJoy()}};renderJoy();
// Tasks
function renderTasks(){$('#taskList').innerHTML=state.tasks.map(t=>`<button class="task ${t.done?'done':''}" data-task="${t.id}">${t.done?'✓':'○'} <span>${escapeHtml(t.text)}</span></button>`).join('')}$('#taskList').onclick=e=>{let b=e.target.closest('[data-task]');if(!b)return;let t=state.tasks.find(x=>x.id===b.dataset.task);t.done=!t.done;save();renderTasks()};$('#addTask').onclick=()=>{let v=$('#taskInput').value.trim();if(!v)return;state.tasks.push({id:crypto.randomUUID(),text:v,done:false});$('#taskInput').value='';save();renderTasks()};$('#resetTasks').onclick=()=>{state.tasks=state.tasks.map(t=>({...t,done:false}));save();renderTasks()};renderTasks();let today=()=>new Date().toISOString().slice(0,10);$('#gratitude').value=state.gratitude[today()]||'';$('#saveGratitude').onclick=()=>{state.gratitude[today()]=$('#gratitude').value;save();toast('Lichtpuntje bewaard')};
// Journal crypto: PBKDF2 + AES-GCM
const enc=new TextEncoder(),dec=new TextDecoder();const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt){let base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptJournal(entries,key){let iv=crypto.getRandomValues(new Uint8Array(12));let data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(entries)));return {iv:b64(iv),data:b64(data)}}
async function decryptJournal(blob,key){let data=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(blob.iv)},key,unb64(blob.data));return JSON.parse(dec.decode(data))}
function updateJournalLock(){let exists=!!localStorage.getItem('rustpuntJournal');$('#lockTitle').textContent=exists?'Ontgrendel je dagboek':'Maak een dagboekwachtwoord';$('#lockHelp').textContent=exists?'Voer je eigen wachtwoord in.':'Je notities worden versleuteld op dit apparaat. Kies minimaal 8 tekens.'}
$('#unlockJournal').onclick=async()=>{let p=$('#journalPassword').value;if(p.length<8){toast('Gebruik minimaal 8 tekens');return}try{let saved=JSON.parse(localStorage.getItem('rustpuntJournal')||'null');let salt=saved?unb64(saved.salt):crypto.getRandomValues(new Uint8Array(16));let key=await derive(p,salt);let entries=saved?await decryptJournal(saved,key):[];journalKey=key;unlockedEntries=entries;if(!saved){let blob=await encryptJournal([],key);localStorage.setItem('rustpuntJournal',JSON.stringify({salt:b64(salt),...blob}))}$('#journalPassword').value='';$('#journalLocked').classList.add('hidden');$('#journalOpen').classList.remove('hidden');renderEntries();toast('Dagboek ontgrendeld')}catch(e){toast('Wachtwoord klopt niet of gegevens zijn beschadigd')}};
async function persistJournal(){let saved=JSON.parse(localStorage.getItem('rustpuntJournal'));let blob=await encryptJournal(unlockedEntries,journalKey);localStorage.setItem('rustpuntJournal',JSON.stringify({salt:saved.salt,...blob}))}
$$('.moodchips button').forEach(b=>b.onclick=()=>{$$('.moodchips button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedEmotion=b.dataset.emotion});
$('#saveEntry').onclick=async()=>{let text=$('#entryText').value.trim();if(!text)return toast('Schrijf eerst iets');unlockedEntries.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),title:$('#entryTitle').value.trim()||'Zonder titel',text,emotion:selectedEmotion});await persistJournal();$('#entryTitle').value='';$('#entryText').value='';selectedEmotion='';$$('.moodchips button').forEach(x=>x.classList.remove('selected'));renderEntries();toast('Notitie versleuteld bewaard')};
function renderEntries(){if(!unlockedEntries)return;let q=$('#searchEntries').value.toLowerCase();let list=unlockedEntries.filter(e=>(e.title+' '+e.text+' '+e.emotion).toLowerCase().includes(q));$('#entryList').innerHTML=list.length?list.map(e=>`<article><button data-entrydel="${e.id}">×</button><h4>${escapeHtml(e.title)}</h4><small>${new Date(e.at).toLocaleString('nl-NL')} ${e.emotion?'· '+escapeHtml(e.emotion):''}</small><p>${escapeHtml(e.text).replace(/\n/g,'<br>')}</p></article>`).join(''):'<p class="fine">Geen notities gevonden.</p>'}$('#searchEntries').oninput=renderEntries;$('#entryList').onclick=async e=>{if(e.target.dataset.entrydel){if(confirm('Deze notitie definitief verwijderen?')){unlockedEntries=unlockedEntries.filter(x=>x.id!==e.target.dataset.entrydel);await persistJournal();renderEntries()}}};
$('#lockJournal').onclick=()=>{unlockedEntries=null;journalKey=null;$('#journalOpen').classList.add('hidden');$('#journalLocked').classList.remove('hidden');toast('Dagboek vergrendeld')};$('#deleteJournal').onclick=()=>{if(confirm('Het volledige versleutelde dagboek verwijderen? Dit kan niet ongedaan worden.')){localStorage.removeItem('rustpuntJournal');unlockedEntries=null;journalKey=null;$('#journalOpen').classList.add('hidden');$('#journalLocked').classList.remove('hidden');updateJournalLock()}};
$('#exportJournal').onclick=()=>{let raw=localStorage.getItem('rustpuntJournal');download('rustpunt-dagboek-versleuteld.json',raw)};
// Insights and export
function renderInsights(){let a=state.checkins.slice(-7);$('#checkinCount').textContent=state.checkins.length;$('#avgMood').textContent=a.length?(a.reduce((s,x)=>s+x.mood,0)/a.length).toFixed(1):'–';$('#avgStimuli').textContent=a.length?(a.reduce((s,x)=>s+x.stimuli,0)/a.length).toFixed(1):'–';$('#bars').innerHTML=a.length?a.map(x=>`<div class="bar" title="Gevoel ${x.mood}, prikkels ${x.stimuli}"><i class="m" style="height:${x.mood*20}%"></i><i class="s" style="height:${x.stimuli*20}%"></i></div>`).join(''):'<p class="fine">Nog geen check-ins.</p>'}$('#exportAll').onclick=()=>download('rustpunt-instellingen.json',JSON.stringify(state,null,2));
// Settings
function applyPrefs(){document.body.classList.toggle('dark',state.prefs.dark);document.body.classList.toggle('quiet',state.prefs.quiet);document.body.classList.toggle('large',state.prefs.large);document.body.classList.toggle('contrast',state.prefs.contrast);$('#darkMode').checked=state.prefs.dark;$('#quietMode').checked=state.prefs.quiet;$('#largeText').checked=state.prefs.large;$('#highContrast').checked=state.prefs.contrast}['dark','quiet','large','contrast'].forEach((k,i)=>{let ids=['darkMode','quietMode','largeText','highContrast'];$('#'+ids[i]).onchange=e=>{state.prefs[k]=e.target.checked;save();applyPrefs()}});$('#quietBtn').onclick=()=>{state.prefs.quiet=!state.prefs.quiet;save();applyPrefs()};applyPrefs();
$('#displayName').value=state.name||'';function greet(){$('#greeting').textContent=state.name?`Fijn dat je er bent, ${state.name}`:'Fijn dat je er bent'}greet();$('#saveName').onclick=()=>{state.name=$('#displayName').value.trim();save();greet();toast('Naam bewaard')};$('#supportName').value=state.support.name||'';$('#supportPhone').value=state.support.phone||'';function support(){if(state.support.phone){$('#supportCall').classList.remove('hidden');$('#supportCall').href='tel:'+state.support.phone;$('#supportCall').textContent='Bel '+(state.support.name||'mijn steuncontact')}}support();$('#saveSupport').onclick=()=>{state.support={name:$('#supportName').value.trim(),phone:$('#supportPhone').value.trim()};save();support();toast('Steuncontact lokaal bewaard')};
$('#setReminder').onclick=async()=>{if(!('Notification'in window))return toast('Meldingen worden niet ondersteund');let p=await Notification.requestPermission();if(p!=='granted')return toast('Geen toestemming voor meldingen');localStorage.setItem('rustpuntReminder',$('#reminderTime').value);toast('Tijd bewaard. Houd er rekening mee dat webbrowsers geen garantie bieden wanneer de app gesloten is.');if($('#reminderTime').value)new Notification('SerenaMind',{body:'Je dagelijkse herinnering staat klaar.'})};$('#reminderTime').value=localStorage.getItem('rustpuntReminder')||'';
$('#clearGeneral').onclick=()=>{if(confirm('Alle niet-dagboekgegevens wissen?')){localStorage.removeItem('rustpuntPlus');location.reload()}};
// Crisis
$('#crisisBtn').onclick=()=>$('#crisisModal').classList.add('show');$('#closeCrisis').onclick=()=>$('#crisisModal').classList.remove('show');
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
updateJournalLock();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
let focusInt=null;$$('[data-focus]').forEach(b=>b.onclick=()=>{clearInterval(focusInt);let left=Number(b.dataset.focus);focusInt=setInterval(()=>{left--;$('#focusTimer').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');if(left<=0){clearInterval(focusInt);$('#focusTimer').textContent='Klaar. Neem een zachte pauze.'}},1000)});$('#stopFocus').onclick=()=>{clearInterval(focusInt);$('#focusTimer').textContent='Gestopt. Dat is ook goed.'};$$('[data-sensory]').forEach(b=>b.onclick=()=>$('#sensoryResult').textContent=b.dataset.sensory);state.parking=state.parking||[];function renderParking(){$('#parkingList').innerHTML=state.parking.map((x,i)=>`<div><button data-pd="${i}">×</button>${escapeHtml(x.text)} <small>${escapeHtml(x.time||'later')}</small></div>`).join('')||'<p class="fine">Nog niets geparkeerd.</p>'}$('#saveParking').onclick=()=>{let text=$('#parkingText').value.trim();if(!text)return;state.parking.push({text,time:$('#parkingTime').value});$('#parkingText').value='';save();renderParking();toast('Gedachte geparkeerd')};$('#parkingList').onclick=e=>{if(e.target.dataset.pd!==undefined){state.parking.splice(+e.target.dataset.pd,1);save();renderParking()}};renderParking();const evenings=['Vandaag is genoeg geweest.','Je hoeft de dag niet perfect af te sluiten om te mogen rusten.','Laat wat openstaat voor nu zacht liggen.'];$('#eveningMessage').onclick=()=>$('#eveningResult').textContent=evenings[Math.floor(Math.random()*evenings.length)];state.calmCard=state.calmCard||{};function renderCalmCard(){let c=state.calmCard;$('#safePlace').value=c.place||'';$('#helpSentence').value=c.sentence||'';$('#helpPerson').value=c.person||'';$('#calmCard').innerHTML=c.place||c.sentence||c.person?`<b>Mijn kaart</b><p>Veiliger plek: ${escapeHtml(c.place||'–')}</p><p>Helpende zin: ${escapeHtml(c.sentence||'–')}</p><p>Contact: ${escapeHtml(c.person||'–')}</p>`:'Nog niet ingevuld.'}$('#saveCalmCard').onclick=()=>{state.calmCard={place:$('#safePlace').value.trim(),sentence:$('#helpSentence').value.trim(),person:$('#helpPerson').value.trim()};save();renderCalmCard();toast('Kalmeerkaart bewaard')};renderCalmCard();
// Uitgebreide persoonlijke hulpkist
$$('[data-feature]').forEach((b,i)=>b.onclick=()=>{$$('[data-feature]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.featurePanel').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.feature+'Feature').classList.remove('hidden')});
state.safety=state.safety||{};['warningSigns','copingSteps','safePeople','avoidActions'].forEach(id=>$('#'+id).value=state.safety[id]||'');$('#saveSafety').onclick=()=>{['warningSigns','copingSteps','safePeople','avoidActions'].forEach(id=>state.safety[id]=$('#'+id).value.trim());save();toast('Signaleringsplan lokaal bewaard')};$('#printSafety').onclick=()=>window.print();
state.sleep=state.sleep||{done:{},bedTime:''};$('#bedTime').value=state.sleep.bedTime||'';$$('[data-sleep]').forEach(x=>{x.checked=!!state.sleep.done[x.dataset.sleep];x.onchange=()=>{state.sleep.done[x.dataset.sleep]=x.checked;save()}});$('#saveSleep').onclick=()=>{state.sleep.bedTime=$('#bedTime').value;save();toast('Avondroutine bewaard')};let windInt;$('#startWinddown').onclick=()=>{clearInterval(windInt);let left=900;windInt=setInterval(()=>{left--;$('#winddownTimer').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');if(left<=0){clearInterval(windInt);$('#winddownTimer').textContent='Je afbouwmoment is afgerond.'}},1000)};
state.wins=state.wins||[];function renderWins(){$('#winsList').innerHTML=state.wins.length?state.wins.map((w,i)=>`<article><button data-windel="${i}">×</button><small>${new Date(w.at).toLocaleDateString('nl-NL')}</small><div>${escapeHtml(w.text)}</div></article>`).join(''):'<p class="fine">Hier komen jouw kleine overwinningen.</p>'}$('#addWin').onclick=()=>{let text=$('#winInput').value.trim();if(!text)return;state.wins.unshift({text,at:new Date().toISOString()});state.wins=state.wins.slice(0,100);$('#winInput').value='';save();renderWins();toast('Overwinning bewaard')};$('#winsList').onclick=e=>{if(e.target.dataset.windel!==undefined){state.wins.splice(+e.target.dataset.windel,1);save();renderWins()}};renderWins();
const needTips={rust:'Maak één plek 5 minuten stiller of zachter.',contact:'Stuur één vertrouwd persoon: “Heb je even ruimte voor contact?”',focus:'Schrijf alleen de allereerste handeling op.',comfort:'Kies warmte, een zachte stof of een vertrouwde geur.',movement:'Beweeg rustig 1 minuut, alleen als dat prettig en veilig voelt.',clarity:'Schrijf op: wat moet nu, wat kan later, wat mag weg?'};$$('[data-need]').forEach(b=>b.onclick=()=>$('#needAnswer').textContent=needTips[b.dataset.need]);
let selectedBody=[];$$('.bodychips button').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');selectedBody=$$('.bodychips button.selected').map(x=>x.textContent)});$('#tension').oninput=e=>$('#tensionValue').textContent=e.target.value+'/5';state.bodyChecks=state.bodyChecks||[];$('#saveBodyCheck').onclick=()=>{state.bodyChecks.push({at:new Date().toISOString(),areas:selectedBody,tension:+$('#tension').value,help:$('#bodyHelp').value.trim()});state.bodyChecks=state.bodyChecks.slice(-30);save();toast('Lichaamscheck bewaard')};
state.customCards=state.customCards||[];const baseCards=['Ik mag het stap voor stap doen.','Rust is geen mislukking.','Ik hoef niet alles vandaag op te lossen.','Mijn grens is informatie.','Een klein veilig moment telt.','Ik mag hulp vragen.'];function nextAffirm(){let all=baseCards.concat(state.customCards);$('#affirmCard strong').textContent=all[Math.floor(Math.random()*all.length)]}$('#nextCard').onclick=nextAffirm;$('#addCard').onclick=()=>{let v=$('#cardInput').value.trim();if(!v)return;state.customCards.push(v);$('#cardInput').value='';save();$('#affirmCard strong').textContent=v;toast('Eigen kaart toegevoegd')};
const basicTips={water:'Neem een paar rustige slokken als dat kan.',food:'Wanneer heb je voor het laatst iets gegeten?',toilet:'Controleer of je naar het toilet moet.',temperature:'Is een laagje kleding erbij of eraf prettiger?',noise:'Kan geluid zachter, voorspelbaarder of tijdelijk weg?',light:'Kan het licht gedimd of minder scherp?'};$$('[data-basic]').forEach(b=>b.onclick=()=>$('#basicAnswer').textContent=basicTips[b.dataset.basic]);

// SerenaMind Professional functies
const modules=['Rust','Dagboek','Opvrolijken','Mijn plan','Toolbox','Meer hulp','Overzicht','Pro functies'];state.modules=state.modules||Object.fromEntries(modules.map(x=>[x,true]));$('#moduleChoices').innerHTML=modules.map(x=>`<label><input type="checkbox" data-module="${x}" ${state.modules[x]?'checked':''}>${x}</label>`).join('');$('#saveModules').onclick=()=>{$$('[data-module]').forEach(x=>state.modules[x.dataset.module]=x.checked);save();toast('Startschermvoorkeuren bewaard')};
state.locale=state.locale||{language:'nl',country:'NL'};$('#language').value=state.locale.language;$('#crisisCountry').value=state.locale.country;const crisisInfo={NL:'Nederland: direct gevaar 112. Suïcidale gedachten: 113 of 0800-0113.',BE:'België: direct gevaar 112. Zelfmoordlijn 1813.',CW:'Curaçao: direct gevaar 911. Neem bij psychische crisis contact op met lokale zorg of huisarts.',AW:'Aruba: direct gevaar 911. Neem bij psychische crisis contact op met lokale zorg of huisarts.',ES:'España: emergencia 112. Línea 024 para conducta suicida.',US:'United States: emergency 911. Suicide & Crisis Lifeline 988.'};function localeInfo(){$('#countryHelp').textContent=crisisInfo[$('#crisisCountry').value]}$('#crisisCountry').onchange=localeInfo;localeInfo();$('#saveLocale').onclick=()=>{state.locale={language:$('#language').value,country:$('#crisisCountry').value};save();toast('Taal en land bewaard. Volledige vertaling is als taalmodule voorbereid.')};
state.contacts=state.contacts||[];function renderContacts(){$('#contactsList').innerHTML=state.contacts.map((c,i)=>`<article><button data-cdel="${i}">×</button><b>${escapeHtml(c.name)}</b> · ${escapeHtml(c.role)}<br><a href="tel:${escapeHtml(c.phone)}">${escapeHtml(c.phone)}</a></article>`).join('')||'<p class="fine">Nog geen extra contacten.</p>'}$('#addContact').onclick=()=>{let name=$('#contactName').value.trim(),phone=$('#contactPhone').value.trim();if(!name||!phone)return toast('Naam en nummer zijn nodig');state.contacts.push({name,phone,role:$('#contactRole').value});save();renderContacts();$('#contactName').value=$('#contactPhone').value=''};$('#contactsList').onclick=e=>{if(e.target.dataset.cdel!==undefined){state.contacts.splice(+e.target.dataset.cdel,1);save();renderContacts()}};renderContacts();
state.proReminders=state.proReminders||[];function renderReminders(){$('#remindersList').innerHTML=state.proReminders.map((x,i)=>`<div><button data-rdel="${i}">×</button><b>${escapeHtml(x.type)}</b> ${escapeHtml(x.time)} ${escapeHtml(x.text)}</div>`).join('')||'<p class="fine">Nog geen herinneringen.</p>'}$('#addReminder').onclick=()=>{if(!$('#proReminderTime').value)return toast('Kies een tijd');state.proReminders.push({type:$('#reminderType').value,time:$('#proReminderTime').value,text:$('#reminderText').value.trim()});save();renderReminders();toast('Herinnering lokaal opgeslagen')};$('#remindersList').onclick=e=>{if(e.target.dataset.rdel!==undefined){state.proReminders.splice(+e.target.dataset.rdel,1);save();renderReminders()}};renderReminders();
state.routine=state.routine||[];function rr(){$('#routineList').innerHTML=state.routine.map((x,i)=>`<li>${escapeHtml(x)} <button data-routine-del="${i}">×</button></li>`).join('')}$$('[data-routine]').forEach(b=>b.onclick=()=>{state.routine.push(b.dataset.routine);save();rr()});$('#routineList').onclick=e=>{if(e.target.dataset.routineDel!==undefined){state.routine.splice(+e.target.dataset.routineDel,1);save();rr()}};$('#clearRoutine').onclick=()=>{state.routine=[];save();rr()};let routineI=0;$('#startRoutine').onclick=()=>{routineI=0;$('#routineNow').textContent=state.routine.length?'Stap 1: '+state.routine[0]:'Voeg eerst stappen toe.'};$('#routineNow').onclick=()=>{if(state.routine.length){routineI=(routineI+1)%state.routine.length;$('#routineNow').textContent=`Stap ${routineI+1}: ${state.routine[routineI]}`}};rr();
function wellbeing(){let a=state.checkins||[];return {gemaakt:new Date().toISOString(),profiel:state.name,checkins:a.length,gemiddeldGevoel:a.length?(a.reduce((q,x)=>q+x.mood,0)/a.length).toFixed(1):null,gemiddeldePrikkels:a.length?(a.reduce((q,x)=>q+x.stimuli,0)/a.length).toFixed(1):null,kleineOverwinningen:state.wins||[],lichaamschecks:state.bodyChecks||[],signaleringsplan:state.safety||{},routine:state.routine||[],notitie:'Vrijwillig gebruikersoverzicht, geen diagnose.'}}$('#exportWellbeing').onclick=()=>download('serenamind-welzijnsoverzicht.json',JSON.stringify(wellbeing(),null,2));$('#printWellbeing').onclick=()=>window.print();
let audioCtx,audioNodes=[];function stopAudio(){audioNodes.forEach(n=>{try{n.stop()}catch{}try{n.disconnect()}catch{}});audioNodes=[];if(audioCtx){audioCtx.close();audioCtx=null}}function sound(type){stopAudio();audioCtx=new(window.AudioContext||webkitAudioContext)();let gain=audioCtx.createGain();gain.gain.value=+$('#soundVolume').value;gain.connect(audioCtx.destination);if(type==='brown'){let len=audioCtx.sampleRate*2,b=audioCtx.createBuffer(1,len,audioCtx.sampleRate),d=b.getChannelData(0),last=0;for(let i=0;i<len;i++){last=(last+.02*(Math.random()*2-1))/1.02;d[i]=last*3.5}let src=audioCtx.createBufferSource();src.buffer=b;src.loop=true;src.connect(gain);src.start();audioNodes=[src,gain]}else{let o=audioCtx.createOscillator(),l=audioCtx.createOscillator(),lg=audioCtx.createGain();o.frequency.value=type==='wave'?174:260;l.frequency.value=type==='wave'?.08:1.7;lg.gain.value=type==='wave'?18:35;l.connect(lg);lg.connect(o.frequency);o.connect(gain);o.start();l.start();audioNodes=[o,l,lg,gain]}}$$('[data-sound]').forEach(b=>b.onclick=()=>sound(b.dataset.sound));$('#stopSound').onclick=stopAudio;$('#soundVolume').oninput=e=>{let g=audioNodes.find(n=>n.gain);if(g)g.gain.value=+e.target.value};
let mediaRecorder,voiceChunks=[];state.voiceMeta=state.voiceMeta||[];function renderVoices(){$('#voiceList').innerHTML=state.voiceMeta.map((x,i)=>`<div>Spraaknotitie ${i+1} · ${new Date(x.at).toLocaleString('nl-NL')}</div>`).join('')||'<p class="fine">Nog geen opname in deze sessie.</p>'}$('#recordVoice').onclick=async()=>{try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);voiceChunks=[];mediaRecorder.ondataavailable=e=>voiceChunks.push(e.data);mediaRecorder.onstop=()=>{let url=URL.createObjectURL(new Blob(voiceChunks,{type:mediaRecorder.mimeType}));let a=document.createElement('audio');a.controls=true;a.src=url;$('#voiceList').prepend(a);state.voiceMeta.push({at:new Date().toISOString(),localOnly:true});save();stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();$('#recordVoice').disabled=true;$('#stopVoice').disabled=false}catch{toast('Microfoon niet beschikbaar of geen toestemming')}};$('#stopVoice').onclick=()=>{if(mediaRecorder)mediaRecorder.stop();$('#recordVoice').disabled=false;$('#stopVoice').disabled=true};renderVoices();
$('#enableBio').onclick=async()=>{if(!window.PublicKeyCredential)return $('#securityMessage').textContent='Biometrie wordt hier niet ondersteund.';$('#securityMessage').textContent='Dit apparaat ondersteunt WebAuthn. Definitieve koppeling vereist een beveiligde server.'};$('#setup2fa').onclick=()=>{$('#securityMessage').textContent='Tweestapscontrole is voorbereid. Voor echte verificatie is een authenticator- of e-mailserver nodig.'};$('#cloudSync').onclick=()=>{$('#syncStatus').textContent='Klaar voor backendkoppeling';$('#securityMessage').textContent='Lokale export is beschikbaar. Echte end-to-end synchronisatie vereist serverinfrastructuur.'};$('#watchMode').onclick=()=>{document.body.classList.toggle('watch');go('calm')};
const widgetTips=['Voel je voeten en kijk naar één rustig punt.','Laat je uitademing vanzelf iets langer worden.','Noem drie kleuren die je ziet.','Ontspan je handen een klein beetje.'];let wi=0;$('#widgetNext').onclick=()=>$('#widgetText').textContent=widgetTips[++wi%widgetTips.length];$('#installHint').onclick=()=>toast('Android: Chrome-menu > App installeren. iPhone: Safari > Delen > Zet op beginscherm.')
$('#exportEncrypted').onclick=()=>{let data={account:currentAccount(),state,journal:localStorage.getItem('rustpuntJournal')};download('serenamind-lokale-backup.json',JSON.stringify(data))};$('#deleteAccountSecure').onclick=()=>{if(!confirm('Account, dagboek en alle lokale SerenaMind-gegevens definitief verwijderen?'))return;let a=currentAccount();if(a)localStorage.removeItem('rustpuntAccount:'+a.username);['rustpuntPlus','rustpuntJournal','rustpuntReminder'].forEach(k=>localStorage.removeItem(k));sessionStorage.clear();location.reload()};
