(() => {
'use strict';
const q=s=>document.querySelector(s);
const key=u=>'rustpuntAccount:'+u;
const encode=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
async function hash(password,salt){const raw=await crypto.subtle.digest('SHA-256',new Uint8Array([...salt,...new TextEncoder().encode(password)]));return encode(raw)}
function status(id,text,good=false){const e=q(id);if(e){e.textContent=text;e.style.color=good?'#397068':'#a83f5d'}}
function avatar(name){const ch=(name[0]||'S').toUpperCase();const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" rx="55" fill="#eee9f8"/><circle cx="100" cy="78" r="38" fill="#7367a8"/><path d="M38 184c8-52 116-52 124 0" fill="#527f86"/><text x="100" y="193" text-anchor="middle" font-family="sans-serif" font-size="18" fill="white">${ch}</text></svg>`;return 'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(svg)))}
function account(){try{const u=localStorage.getItem('serenaCurrentUser')||sessionStorage.getItem('serenaSessionUser');return u?JSON.parse(localStorage.getItem(key(u))||'null'):null}catch{return null}}
function showApp(a){const auth=q('#authScreen');document.body.classList.add('authenticated');if(auth){auth.hidden=true;auth.classList.add('hidden');auth.style.cssText='display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important';auth.setAttribute('aria-hidden','true');auth.inert=true}const pic=a?.profile?.avatar||avatar(a?.profile?.name||'S');['#headerAvatar','#settingsAvatar'].forEach(id=>{const e=q(id);if(e)e.src=pic});const g=q('#greeting');if(g)g.textContent='Fijn dat je er bent'+(a?.profile?.name?', '+a.profile.name:'');const pu=q('#profileUsername');if(pu)pu.textContent='@'+(a?.username||'gebruiker');window.scrollTo(0,0)}
function showAuth(){const auth=q('#authScreen');document.body.classList.remove('authenticated');if(auth){auth.hidden=false;auth.classList.remove('hidden','authClosing');auth.style.cssText='';auth.removeAttribute('aria-hidden');auth.inert=false}}
function tab(which){q('#loginForm')?.classList.toggle('hidden',which!=='login');q('#registerForm')?.classList.toggle('hidden',which!=='register');document.querySelectorAll('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===which))}
function replaceButton(id,fn){const old=q(id);if(!old)return;const b=old.cloneNode(true);b.type='button';old.replaceWith(b);b.addEventListener('click',fn,{capture:true})}
async function register(e){e.preventDefault();e.stopImmediatePropagation();const name=(q('#registerName')?.value||'').trim(),user=(q('#registerUser')?.value||'').trim().toLowerCase(),p=q('#registerPass')?.value||'',p2=q('#registerPass2')?.value||'',role=q('#registerRole')?.value||'client';if(name.length<2)return status('#registerStatus','Vul een naam of bijnaam in.');if(!/^[a-z0-9._-]{3,30}$/.test(user))return status('#registerStatus','Gebruikersnaam: 3-30 kleine letters, cijfers, punt, streepje of underscore.');if(p.length<8)return status('#registerStatus','Gebruik minimaal 8 tekens voor het wachtwoord.');if(p!==p2)return status('#registerStatus','De wachtwoorden zijn niet gelijk.');if(localStorage.getItem(key(user)))return status('#registerStatus','Deze gebruikersnaam bestaat al op dit apparaat. Kies Inloggen of een andere naam.');const b=q('#registerBtn');b.disabled=true;b.textContent='Profiel wordt gemaakt…';try{const salt=crypto.getRandomValues(new Uint8Array(16)),h=await hash(p,salt);let photo='';try{photo=window.pendingAvatar||''}catch{}const a={version:13,username:user,salt:encode(salt),hash:h,profile:{name,role,avatar:photo||avatar(name)},created:new Date().toISOString()};localStorage.setItem(key(user),JSON.stringify(a));localStorage.setItem('serenaCurrentUser',user);localStorage.setItem('serenaLastActivity',String(Date.now()));if(!localStorage.getItem(key(user)))throw Error('storage');status('#registerStatus','Profiel aangemaakt.',true);showApp(a)}catch(err){console.error(err);status('#registerStatus','Opslaan lukte niet. Gebruik de HTTPS-link buiten privémodus.');b.disabled=false;b.textContent='Profiel maken'}}
async function login(e){e.preventDefault();e.stopImmediatePropagation();const user=(q('#loginUser')?.value||'').trim().toLowerCase(),p=q('#loginPass')?.value||'';let a=null;try{a=JSON.parse(localStorage.getItem(key(user))||'null')}catch{}if(!a)return status('#loginSecurityMessage','Account niet gevonden op dit apparaat.');try{const salt=Uint8Array.from(atob(a.salt),c=>c.charCodeAt(0));if(await hash(p,salt)!==a.hash)return status('#loginSecurityMessage','Gebruikersnaam of wachtwoord klopt niet.');if(q('#rememberLogin')?.checked!==false){localStorage.setItem('serenaCurrentUser',user);sessionStorage.removeItem('serenaSessionUser')}else{sessionStorage.setItem('serenaSessionUser',user);localStorage.removeItem('serenaCurrentUser')}localStorage.setItem('serenaLastActivity',String(Date.now()));showApp(a)}catch(err){console.error(err);status('#loginSecurityMessage','Inloggen is mislukt. Probeer opnieuw.')}}
function boot(){document.querySelectorAll('[data-auth]').forEach(old=>{const b=old.cloneNode(true);b.type='button';old.replaceWith(b);b.addEventListener('click',e=>{e.preventDefault();tab(b.dataset.auth)})});replaceButton('#registerBtn',register);replaceButton('#loginBtn',login);const logout=q('#logoutBtn');if(logout)logout.onclick=()=>{localStorage.removeItem('serenaCurrentUser');sessionStorage.removeItem('serenaSessionUser');location.reload()};const a=account();a?showApp(a):showAuth();window.addEventListener('pageshow',()=>{const x=account();x?showApp(x):showAuth()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
