(() => {
'use strict';
const $=s=>document.querySelector(s), accountKey=u=>'serenaAccount:'+u;
const bytes64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
async function digest(password,salt){const p=new TextEncoder().encode(password),all=new Uint8Array(salt.length+p.length);all.set(salt);all.set(p,salt.length);return bytes64(await crypto.subtle.digest('SHA-256',all))}
function message(id,text,ok=false){const e=$(id);if(e){e.textContent=text;e.classList.toggle('ok',ok)}}
function current(){try{const u=localStorage.getItem('serenaSignedIn')||sessionStorage.getItem('serenaSignedIn');return u?JSON.parse(localStorage.getItem(accountKey(u))||'null'):null}catch{return null}}
function defaultAvatar(name){const c=(name?.[0]||'S').toUpperCase();return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect width="200" height="200" rx="55" fill="#eee9f8"/><circle cx="100" cy="72" r="38" fill="#7367a8"/><path d="M35 190c8-58 122-58 130 0" fill="#527f86"/><text x="100" y="192" text-anchor="middle" fill="white" font-size="18">${c}</text></svg>`)}`}
function enter(a){document.body.classList.add('authenticated');const screen=$('#authScreen');if(screen){screen.hidden=true;screen.setAttribute('aria-hidden','true');screen.style.display='none';screen.inert=true}const avatar=a.profile?.avatar||defaultAvatar(a.profile?.name);['#headerAvatar','#settingsAvatar'].forEach(id=>{const e=$(id);if(e)e.src=avatar});const g=$('#greeting');if(g)g.textContent=`Fijn dat je er bent${a.profile?.name?', '+a.profile.name:''}`;const u=$('#profileUsername');if(u)u.textContent='@'+a.username;window.scrollTo(0,0)}
function leave(){document.body.classList.remove('authenticated');const screen=$('#authScreen');if(screen){screen.hidden=false;screen.removeAttribute('aria-hidden');screen.style.display='';screen.inert=false}}
function tab(name){$('#loginForm')?.classList.toggle('hidden',name!=='login');$('#registerForm')?.classList.toggle('hidden',name!=='register');document.querySelectorAll('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===name))}
async function register(){message('#registerStatus','');const name=($('#registerName')?.value||'').trim(),username=($('#registerUser')?.value||'').trim().toLowerCase(),password=$('#registerPass')?.value||'',again=$('#registerPass2')?.value||'',role=$('#registerRole')?.value||'client';if(name.length<2)return message('#registerStatus','Vul een naam of bijnaam in.');if(!/^[a-z0-9._-]{3,30}$/.test(username))return message('#registerStatus','Gebruikersnaam: 3-30 kleine letters, cijfers, punt, streepje of underscore.');if(password.length<8)return message('#registerStatus','Gebruik minimaal 8 tekens voor het wachtwoord.');if(password!==again)return message('#registerStatus','De wachtwoorden zijn niet gelijk.');if(localStorage.getItem(accountKey(username)))return message('#registerStatus','Deze gebruikersnaam bestaat al op dit apparaat.');const b=$('#registerBtn');if(b.disabled)return;b.disabled=true;b.textContent='Profiel wordt gemaakt...';try{const salt=crypto.getRandomValues(new Uint8Array(16)),hash=await digest(password,salt),a={version:14,username,salt:bytes64(salt),hash,profile:{name,role,avatar:defaultAvatar(name)},created:new Date().toISOString()};localStorage.setItem(accountKey(username),JSON.stringify(a));localStorage.setItem('serenaSignedIn',username);localStorage.setItem('serenaLastActivity',String(Date.now()));enter(a)}catch(e){console.error(e);message('#registerStatus','Opslaan lukt niet. Gebruik de HTTPS-link buiten privemodus.');b.disabled=false;b.textContent='Profiel maken'}}
async function login(){message('#loginSecurityMessage','');const username=($('#loginUser')?.value||'').trim().toLowerCase(),password=$('#loginPass')?.value||'';let a;try{a=JSON.parse(localStorage.getItem(accountKey(username))||'null')}catch{}if(!a)return message('#loginSecurityMessage','Account niet gevonden op dit apparaat.');try{const salt=Uint8Array.from(atob(a.salt),c=>c.charCodeAt(0));if(await digest(password,salt)!==a.hash)return message('#loginSecurityMessage','Gebruikersnaam of wachtwoord klopt niet.');if($('#rememberLogin')?.checked!==false){localStorage.setItem('serenaSignedIn',username);sessionStorage.removeItem('serenaSignedIn')}else{sessionStorage.setItem('serenaSignedIn',username);localStorage.removeItem('serenaSignedIn')}enter(a)}catch(e){console.error(e);message('#loginSecurityMessage','Inloggen is mislukt. Probeer opnieuw.')}}
// Capture before any legacy listeners, reliable on click and touch-generated click.
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-auth]')){e.preventDefault();e.stopImmediatePropagation();tab(b.dataset.auth)}else if(b.id==='registerBtn'){e.preventDefault();e.stopImmediatePropagation();register()}else if(b.id==='loginBtn'){e.preventDefault();e.stopImmediatePropagation();login()}else if(b.id==='logoutBtn'){e.preventDefault();e.stopImmediatePropagation();localStorage.removeItem('serenaSignedIn');sessionStorage.removeItem('serenaSignedIn');leave()}},true);
function boot(){document.querySelectorAll('button').forEach(b=>b.type='button');const a=current();a?enter(a):leave()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.addEventListener('pageshow',()=>{const a=current();a?enter(a):leave()});
})();