import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const cfg=window.SERENAMIND_CONFIG||{};
const configured=cfg.SUPABASE_URL?.startsWith('https://')&&cfg.SUPABASE_ANON_KEY?.startsWith('sb_publishable_');
const remember=localStorage.getItem('serenamindRemember')==='true';
const sessionStore={getItem:k=>sessionStorage.getItem(k),setItem:(k,v)=>sessionStorage.setItem(k,v),removeItem:k=>sessionStorage.removeItem(k)};
const supabase=configured?createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,storage:remember?localStorage:sessionStore,autoRefreshToken:true,detectSessionInUrl:true}}):null;
let activePeer=null,channel=null,pendingRecovery=null;
const INTERNAL_DOMAIN='agnsklwkmaudqmbmcxuj.supabase.co';
function status(message,type='info'){const e=q('#authStatus');if(e){e.textContent=message;e.className='authStatus '+type}if(window.toast)toast(message)}
function switchAuth(which){qa('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===which));q('#loginForm')?.classList.toggle('hidden',which!=='login');q('#registerForm')?.classList.toggle('hidden',which!=='register');status('')}
function normalizeUsername(v){return v.trim().toLowerCase()}
function validUsername(v){return /^[a-z0-9][a-z0-9._-]{2,29}$/.test(v)}
function internalEmail(username){return username+'@'+INTERNAL_DOMAIN}
function makeRecoveryCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',a=new Uint8Array(16);crypto.getRandomValues(a);return [...a].map((x,i)=>(i&&i%4===0?'-':'')+chars[x%chars.length]).join('')}
async function hashRecovery(code){const data=new TextEncoder().encode(code.replaceAll('-','').toUpperCase());const raw=await crypto.subtle.digest('SHA-256',data);return btoa(String.fromCharCode(...new Uint8Array(raw)))}
function friendly(error){const m=(error?.message||'').toLowerCase();if(m.includes('already')||m.includes('registered')||m.includes('duplicate'))return 'Deze gebruikersnaam bestaat al.';if(m.includes('rate'))return 'Te veel pogingen. Wacht even en probeer opnieuw.';if(m.includes('signup')&&m.includes('disabled'))return 'Nieuwe registraties staan uit in Supabase.';if(m.includes('email')&&m.includes('confirm'))return 'Zet Confirm email uit in Supabase.';return 'Account maken is niet gelukt: '+(error?.message||'onbekende fout')}
async function loadProfile(user){let {data,error}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)console.warn(error);const name=data?.display_name||user.user_metadata?.display_name||user.user_metadata?.username||'Gebruiker',avatar=data?.avatar_url||defaultAvatar(name);q('#authScreen').classList.add('hidden');q('#headerAvatar').src=avatar;q('#settingsAvatar').src=avatar;q('#profileUsername').textContent='@'+(data?.username||user.user_metadata?.username||'gebruiker');state.name=name;greet()}
async function withTimeout(promise,ms=15000){let timer;const timeout=new Promise((_,reject)=>timer=setTimeout(()=>reject(new Error('TIMEOUT')),ms));try{return await Promise.race([promise,timeout])}finally{clearTimeout(timer)}}
async function register(){const btn=q('#registerBtn'),retry=q('#retryRegister'),username=normalizeUsername(q('#registerUser').value),name=q('#registerName').value.trim(),password=q('#registerPass').value,password2=q('#registerPass2').value;if(!validUsername(username))return status('Gebruik 3 tot 30 kleine letters, cijfers, punt, streepje of underscore.','error');if(!name)return status('Vul een naam of bijnaam in.','error');if(password.length<10)return status('Het wachtwoord moet minimaal 10 tekens hebben.','error');if(password!==password2)return status('De wachtwoorden zijn niet gelijk.','error');if(!q('#recoveryAgree').checked)return status('Vink aan dat je de herstelcode veilig bewaart.','error');btn.disabled=true;btn.textContent='Account wordt gemaakt…';retry.classList.add('hidden');status('Verbinding controleren…','info');try{if(!navigator.onLine)throw new Error('OFFLINE');const recovery=makeRecoveryCode(),recovery_hash=await hashRecovery(recovery);status('Account opslaan…','info');const result=await withTimeout(supabase.auth.signUp({email:internalEmail(username),password,options:{data:{username,display_name:name,recovery_hash}}}),15000);const {data,error}=result;if(error)throw error;if(!data.session)throw new Error('CONFIRM_EMAIL');pendingRecovery={code:recovery,user:data.user,username,name,recovery_hash};q('#recoveryCodeDisplay').textContent=recovery;q('#recoveryModal').classList.add('show');status('Account gemaakt. Bewaar nu je herstelcode.','success')}catch(e){console.error('SerenaMind registration',e);retry.classList.remove('hidden');if(e.message==='TIMEOUT')status('De verbinding met Supabase duurde te lang. Controleer internet of een content blocker en probeer opnieuw.','error');else if(e.message==='OFFLINE')status('Geen internetverbinding.','error');else if(e.message==='CONFIRM_EMAIL')status('Supabase heeft het account ontvangen, maar Confirm email staat nog AAN. Zet Confirm email UIT en gebruik daarna een nieuwe gebruikersnaam.','error');else status(friendly(e),'error')}finally{btn.disabled=false;btn.textContent='Account maken'}}

async function finishRegistration(){if(!pendingRecovery)return;const {error}=await supabase.from('profiles').upsert({id:pendingRecovery.user.id,username:pendingRecovery.username,display_name:pendingRecovery.name,recovery_hash:pendingRecovery.recovery_hash},{onConflict:'id'});if(error)return status('Profiel opslaan mislukt: '+error.message,'error');q('#recoveryModal').classList.remove('show');await loadProfile(pendingRecovery.user);pendingRecovery=null}
async function login(){const username=normalizeUsername(q('#loginUser').value),password=q('#loginPass').value;if(!validUsername(username))return status('Controleer je gebruikersnaam.','error');localStorage.setItem('serenamindRemember',q('#rememberLogin').checked?'true':'false');status('Inloggen…');const {data,error}=await supabase.auth.signInWithPassword({email:internalEmail(username),password});if(error)return status('Gebruikersnaam of wachtwoord is onjuist.','error');await loadProfile(data.user)}
async function logout(scope='local'){try{await supabase.auth.signOut({scope})}finally{localStorage.removeItem('serenamindRemember');sessionStorage.clear();location.reload()}}
async function boot(){qa('[data-auth]').forEach(b=>b.onclick=()=>switchAuth(b.dataset.auth));if(!configured){status('Supabase-configuratie ontbreekt of is ongeldig.','error');return}q('#registerBtn').onclick=register;q('#retryRegister').onclick=register;q('#loginBtn').onclick=login;q('#finishRegistration').onclick=finishRegistration;q('#confirmRecoverySaved').onchange=e=>q('#finishRegistration').disabled=!e.target.checked;q('#copyRecoveryCode').onclick=async()=>{await navigator.clipboard.writeText(q('#recoveryCodeDisplay').textContent);status('Herstelcode gekopieerd.','success')};q('#downloadRecoveryCode').onclick=()=>{const code=q('#recoveryCodeDisplay').textContent,blob=new Blob(['SerenaMind herstelcode\nGebruikersnaam: '+q('#registerUser').value+'\nHerstelcode: '+code+'\n\nBewaar dit bestand veilig.'],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SerenaMind-herstelcode.txt';a.click();URL.revokeObjectURL(a.href)};q('#forgotBtn').onclick=()=>q('#recoverAccountModal').classList.add('show');q('#closeRecover').onclick=()=>q('#recoverAccountModal').classList.remove('show');q('#submitRecovery').onclick=async()=>{const username=normalizeUsername(q('#recoverUsername').value),code=q('#recoverCode').value.trim();if(!username||!code)return status('Vul gebruikersnaam en herstelcode in.','error');const {data,error}=await supabase.rpc('create_recovery_request',{p_username:username,p_recovery_hash:await hashRecovery(code),p_note:q('#recoverNote').value.trim()});if(error)return status(error.message,'error');status('Herstelverzoek '+data+' is aangemaakt.','success');q('#recoverAccountModal').classList.remove('show')};q('#logoutBtn').onclick=()=>logout('local');q('#headerLogoutBtn').onclick=()=>logout('local');q('#logoutAllBtn').onclick=()=>confirm('Op alle apparaten uitloggen?')&&logout('global');q('#profileMenuBtn').onclick=()=>q('#profileMenu').classList.toggle('hidden');const {data:{session},error}=await supabase.auth.getSession();if(error)status(error.message,'error');if(session)await loadProfile(session.user);else q('#authScreen').classList.remove('hidden');await loadPeers()}
async function me(){return (await supabase.auth.getUser()).data.user}
q('#createInvite').onclick=async()=>{if(!configured)return note('Koppel eerst Supabase');let user=await me(),code=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase(),expires=new Date(Date.now()+24*3600e3).toISOString();let {error}=await supabase.from('peer_invites').insert({owner_id:user.id,code,expires_at:expires});if(error)return note(error.message);q('#inviteCode').textContent=code;note('Code is 24 uur geldig')};
q('#joinPeer').onclick=async()=>{let code=q('#joinCode').value.trim().toUpperCase(),{data,error}=await supabase.rpc('accept_peer_invite',{invite_code:code});if(error)return note(error.message);note('Maatje gekoppeld');q('#joinCode').value='';await loadPeers()};
async function loadPeers(){if(!configured)return;let user=await me();if(!user)return;let {data,error}=await supabase.rpc('my_peer_connections');if(error)return;q('#peerList').innerHTML=data?.length?data.map(x=>`<button class="peerButton" data-peer="${x.connection_id}" data-name="${escapeHtml(x.peer_name)}">♧ ${escapeHtml(x.peer_name)}</button>`).join(''):'<p class="fine">Nog geen gekoppelde maatjes.</p>'}
q('#peerList').onclick=e=>{let b=e.target.closest('[data-peer]');if(b)openChat(b.dataset.peer,b.dataset.name)};q('#closePeerChat').onclick=()=>{q('#peerChat').classList.add('hidden');channel?.unsubscribe()};
async function openChat(id,name){activePeer=id;q('#peerChat').classList.remove('hidden');q('#peerChatName').textContent=name;await messages();channel?.unsubscribe();channel=supabase.channel('peer-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'peer_messages',filter:'connection_id=eq.'+id},messages).subscribe()}
async function messages(){let {data}=await supabase.from('peer_messages').select('id,sender_id,body,created_at').eq('connection_id',activePeer).order('created_at');let user=await me();q('#peerMessages').innerHTML=(data||[]).map(x=>`<div class="peerMsg ${x.sender_id===user.id?'mine':''}">${escapeHtml(x.body)}<small>${new Date(x.created_at).toLocaleString('nl-NL')}</small></div>`).join('')}
q('#sendPeerMessage').onclick=async()=>{let body=q('#peerMessage').value.trim();if(!body||!activePeer)return;let user=await me(),{error}=await supabase.from('peer_messages').insert({connection_id:activePeer,sender_id:user.id,body});if(error)return note(error.message);q('#peerMessage').value=''};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
