import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.SERENAMIND_CONFIG||{},configured=cfg.SUPABASE_URL?.startsWith('https://')&&!cfg.SUPABASE_URL.includes('VUL_HIER')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('VUL_HIER');
const remember=localStorage.getItem('serenamindRemember')==='true';const memoryStore={getItem:k=>sessionStorage.getItem(k),setItem:(k,v)=>sessionStorage.setItem(k,v),removeItem:k=>sessionStorage.removeItem(k)};const supabase=configured?createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,storage:remember?localStorage:memoryStore,autoRefreshToken:true,detectSessionInUrl:true}}):null;let activePeer=null,channel=null;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];function note(t){if(window.toast)toast(t);else alert(t)}
function profileView(user,profile){q('#authScreen').classList.add('hidden');let name=profile?.display_name||user.user_metadata?.display_name||user.email.split('@')[0],avatar=profile?.avatar_url||user.user_metadata?.avatar_url||defaultAvatar(name);q('#headerAvatar').src=avatar;q('#settingsAvatar').src=avatar;q('#profileUsername').textContent='@'+(profile?.username||user.user_metadata?.username||name);state.name=name;greet()}
async function loadProfile(user){let {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();profileView(user,data)}
async function boot(){if(!configured){q('#lockHelp').insertAdjacentHTML('afterend','<p class="setupWarning">Database nog niet gekoppeld. Vul config.js in volgens SUPABASE-INSTALLATIE.md.</p>');return}let {data:{session}}=await supabase.auth.getSession();if(session)await loadProfile(session.user);else q('#authScreen').classList.remove('hidden');
q('#registerBtn').onclick=async()=>{let email=q('#registerEmail').value.trim(),username=q('#registerUser').value.trim().toLowerCase(),name=q('#registerName').value.trim(),password=q('#registerPass').value;if(password!==q('#registerPass2').value)return note('Wachtwoorden zijn niet gelijk');if(password.length<8)return note('Gebruik minimaal 8 tekens');let {data,error}=await supabase.auth.signUp({email,password,options:{data:{username,display_name:name}}});if(error)return note(error.message);if(data.user&&data.session)await supabase.from('profiles').upsert({id:data.user.id,username,display_name:name,avatar_url:null});note(data.session?'Account gemaakt':'Controleer je e-mail om het account te bevestigen')};
q('#loginBtn').onclick=async()=>{localStorage.setItem('serenamindRemember',q('#rememberLogin').checked?'true':'false');let {data,error}=await supabase.auth.signInWithPassword({email:q('#loginUser').value.trim(),password:q('#loginPass').value});if(error)return note('Inloggen mislukt: '+error.message);await loadProfile(data.user)};
q('#forgotBtn').onclick=async()=>{let email=q('#loginUser').value.trim();if(!email)return note('Vul eerst je e-mailadres in');let {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});note(error?error.message:'Herstelmail verzonden')};
async function logout(scope='local'){try{await supabase.auth.signOut({scope})}finally{localStorage.removeItem('serenamindRemember');sessionStorage.clear();location.reload()}}q('#logoutBtn').onclick=()=>logout('local');q('#headerLogoutBtn').onclick=()=>logout('local');q('#logoutAllBtn').onclick=()=>{if(confirm('Wil je op alle apparaten uitloggen?'))logout('global')};q('#profileMenuBtn').onclick=()=>q('#profileMenu').classList.toggle('hidden');
supabase.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY'){let p=prompt('Kies een nieuw wachtwoord van minimaal 8 tekens');if(p?.length>=8){let {error}=await supabase.auth.updateUser({password:p});note(error?error.message:'Wachtwoord aangepast')}}if(session&&event==='SIGNED_IN')await loadProfile(session.user)});await loadPeers()}
async function me(){return (await supabase.auth.getUser()).data.user}
q('#createInvite').onclick=async()=>{if(!configured)return note('Koppel eerst Supabase');let user=await me(),code=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase(),expires=new Date(Date.now()+24*3600e3).toISOString();let {error}=await supabase.from('peer_invites').insert({owner_id:user.id,code,expires_at:expires});if(error)return note(error.message);q('#inviteCode').textContent=code;note('Code is 24 uur geldig')};
q('#joinPeer').onclick=async()=>{let code=q('#joinCode').value.trim().toUpperCase(),{data,error}=await supabase.rpc('accept_peer_invite',{invite_code:code});if(error)return note(error.message);note('Maatje gekoppeld');q('#joinCode').value='';await loadPeers()};
async function loadPeers(){if(!configured)return;let user=await me();if(!user)return;let {data,error}=await supabase.rpc('my_peer_connections');if(error)return;q('#peerList').innerHTML=data?.length?data.map(x=>`<button class="peerButton" data-peer="${x.connection_id}" data-name="${escapeHtml(x.peer_name)}">♧ ${escapeHtml(x.peer_name)}</button>`).join(''):'<p class="fine">Nog geen gekoppelde maatjes.</p>'}
q('#peerList').onclick=e=>{let b=e.target.closest('[data-peer]');if(b)openChat(b.dataset.peer,b.dataset.name)};q('#closePeerChat').onclick=()=>{q('#peerChat').classList.add('hidden');channel?.unsubscribe()};
async function openChat(id,name){activePeer=id;q('#peerChat').classList.remove('hidden');q('#peerChatName').textContent=name;await messages();channel?.unsubscribe();channel=supabase.channel('peer-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'peer_messages',filter:'connection_id=eq.'+id},messages).subscribe()}
async function messages(){let {data}=await supabase.from('peer_messages').select('id,sender_id,body,created_at').eq('connection_id',activePeer).order('created_at');let user=await me();q('#peerMessages').innerHTML=(data||[]).map(x=>`<div class="peerMsg ${x.sender_id===user.id?'mine':''}">${escapeHtml(x.body)}<small>${new Date(x.created_at).toLocaleString('nl-NL')}</small></div>`).join('')}
q('#sendPeerMessage').onclick=async()=>{let body=q('#peerMessage').value.trim();if(!body||!activePeer)return;let user=await me(),{error}=await supabase.from('peer_messages').insert({connection_id:activePeer,sender_id:user.id,body});if(error)return note(error.message);q('#peerMessage').value=''};boot();