import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.SERENAMIND_CONFIG||{},configured=cfg.SUPABASE_URL?.startsWith('https://')&&!cfg.SUPABASE_URL.includes('VUL_HIER')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('VUL_HIER');
const remember=localStorage.getItem('serenamindRemember')==='true';const memoryStore={getItem:k=>sessionStorage.getItem(k),setItem:(k,v)=>sessionStorage.setItem(k,v),removeItem:k=>sessionStorage.removeItem(k)};const supabase=configured?createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,storage:remember?localStorage:memoryStore,autoRefreshToken:true,detectSessionInUrl:true}}):null;let activePeer=null,channel=null;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];function switchAuth(which){qa('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===which));q('#loginForm')?.classList.toggle('hidden',which!=='login');q('#registerForm')?.classList.toggle('hidden',which!=='register')}function note(t){if(window.toast)toast(t);else alert(t)}
function profileView(user,profile){q('#authScreen').classList.add('hidden');let name=profile?.display_name||user.user_metadata?.display_name||user.email.split('@')[0],avatar=profile?.avatar_url||user.user_metadata?.avatar_url||defaultAvatar(name);q('#headerAvatar').src=avatar;q('#settingsAvatar').src=avatar;q('#profileUsername').textContent='@'+(profile?.username||user.user_metadata?.username||name);state.name=name;greet()}
async function loadProfile(user){let {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();profileView(user,data)}
async function boot(){qa('[data-auth]').forEach(b=>{b.onclick=()=>switchAuth(b.dataset.auth)});if(!configured){q('#lockHelp').insertAdjacentHTML('afterend','<p class="setupWarning">Database nog niet gekoppeld. Vul config.js in volgens SUPABASE-INSTALLATIE.md.</p>');return}let {data:{session}}=await supabase.auth.getSession();if(session)await loadProfile(session.user);else q('#authScreen').classList.remove('hidden');
q('#registerBtn').onclick=async()=>{const btn=q('#registerBtn');btn.disabled=true;btn.textContent='Account wordt gemaakt…';try{let username=q('#registerUser').value.trim().toLowerCase(),name=q('#registerName').value.trim(),password=q('#registerPass').value;if(!/^[a-z0-9._-]{3,30}$/.test(username))return note('Gebruik 3 tot 30 letters, cijfers, punten, streepjes of underscores');if(!name)return note('Vul je naam of bijnaam in');if(password.length<10)return note('Gebruik minimaal 10 tekens');if(password!==q('#registerPass2').value)return note('Wachtwoorden zijn niet gelijk');if(!q('#recoveryAgree').checked)return note('Bevestig dat je de herstelcode zult bewaren');let recovery=makeRecoveryCode(),recoveryHash=await hashRecovery(recovery),email=internalEmail(username);let {data,error}=await supabase.auth.signUp({email,password,options:{data:{username,display_name:name,recovery_hash:recoveryHash}}});if(error)return note(friendlyAuthError(error));if(!data.session)return note('Schakel in Supabase e-mailbevestiging uit voor gebruikersnaamaccounts');pendingRecovery={code:recovery,user:data.user};q('#recoveryCodeDisplay').textContent=recovery;q('#recoveryModal').classList.add('show')}catch(e){note('Registratie mislukt: '+(e.message||e))}finally{btn.disabled=false;btn.textContent='Account maken'}};
q('#loginBtn').onclick=async()=>{localStorage.setItem('serenamindRemember',q('#rememberLogin').checked?'true':'false');let username=q('#loginUser').value.trim().toLowerCase();if(!/^[a-z0-9._-]{3,30}$/.test(username))return note('Controleer je gebruikersnaam');let {data,error}=await supabase.auth.signInWithPassword({email:internalEmail(username),password:q('#loginPass').value});if(error)return note('Gebruikersnaam of wachtwoord is onjuist');await loadProfile(data.user)};
q('#forgotBtn').onclick=()=>q('#recoverAccountModal').classList.add('show');
async function logout(scope='local'){try{await supabase.auth.signOut({scope})}finally{localStorage.removeItem('serenamindRemember');sessionStorage.clear();location.reload()}}q('#logoutBtn').onclick=()=>logout('local');q('#headerLogoutBtn').onclick=()=>logout('local');q('#logoutAllBtn').onclick=()=>{if(confirm('Wil je op alle apparaten uitloggen?'))logout('global')};q('#profileMenuBtn').onclick=()=>q('#profileMenu').classList.toggle('hidden');


const USER_DOMAIN='agnsklwkmaudqmbmcxuj.supabase.co';let pendingRecovery=null;
function internalEmail(username){return username+'@'+USER_DOMAIN}
function makeRecoveryCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let parts=[];for(let p=0;p<4;p++){let v='';for(let i=0;i<4;i++)v+=chars[crypto.getRandomValues(new Uint8Array(1))[0]%chars.length];parts.push(v)}return parts.join('-')}
async function hashRecovery(code){let raw=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code.replaceAll('-','').toUpperCase()));return btoa(String.fromCharCode(...new Uint8Array(raw)))}
function friendlyAuthError(e){let m=(e.message||'').toLowerCase();if(m.includes('already')||m.includes('registered'))return 'Deze gebruikersnaam bestaat al';if(m.includes('email')&&m.includes('invalid'))return 'De interne gebruikersidentiteit werd geweigerd. Gebruik SerenaMind v1.6.1.';if(m.includes('rate'))return 'Te veel pogingen. Wacht een minuut en probeer opnieuw.';return 'Registratie is niet gelukt: '+(e.message||'onbekende fout')}
q('#confirmRecoverySaved').onchange=e=>q('#finishRegistration').disabled=!e.target.checked;
q('#copyRecoveryCode').onclick=async()=>{await navigator.clipboard.writeText(q('#recoveryCodeDisplay').textContent);note('Herstelcode gekopieerd')};
q('#downloadRecoveryCode').onclick=()=>{let code=q('#recoveryCodeDisplay').textContent,blob=new Blob(['SerenaMind herstelcode\nGebruikersnaam: '+q('#registerUser').value+'\nHerstelcode: '+code+'\n\nBewaar dit bestand veilig.'],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SerenaMind-herstelcode.txt';a.click();URL.revokeObjectURL(a.href)};
q('#finishRegistration').onclick=async()=>{if(!pendingRecovery)return;let {error}=await supabase.from('profiles').upsert({id:pendingRecovery.user.id,username:q('#registerUser').value.trim().toLowerCase(),display_name:q('#registerName').value.trim(),recovery_hash:await hashRecovery(pendingRecovery.code)});if(error)return note(error.message);q('#recoveryModal').classList.remove('show');await loadProfile(pendingRecovery.user);pendingRecovery=null};
q('#closeRecover').onclick=()=>q('#recoverAccountModal').classList.remove('show');
q('#submitRecovery').onclick=async()=>{let username=q('#recoverUsername').value.trim().toLowerCase(),code=q('#recoverCode').value.trim();if(!username||!code)return note('Vul gebruikersnaam en herstelcode in');let {data,error}=await supabase.rpc('create_recovery_request',{p_username:username,p_recovery_hash:await hashRecovery(code),p_note:q('#recoverNote').value.trim()});if(error)return note(error.message);note('Herstelverzoek '+data+' is aangemaakt. Noteer dit nummer en neem contact op met de beheerder.');q('#recoverAccountModal').classList.remove('show')};
supabase.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY'){let p=prompt('Kies een nieuw wachtwoord van minimaal 8 tekens');if(p?.length>=8){let {error}=await supabase.auth.updateUser({password:p});note(error?error.message:'Wachtwoord aangepast')}}if(session&&event==='SIGNED_IN')await loadProfile(session.user)});await loadPeers()}
async function me(){return (await supabase.auth.getUser()).data.user}
q('#createInvite').onclick=async()=>{if(!configured)return note('Koppel eerst Supabase');let user=await me(),code=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase(),expires=new Date(Date.now()+24*3600e3).toISOString();let {error}=await supabase.from('peer_invites').insert({owner_id:user.id,code,expires_at:expires});if(error)return note(error.message);q('#inviteCode').textContent=code;note('Code is 24 uur geldig')};
q('#joinPeer').onclick=async()=>{let code=q('#joinCode').value.trim().toUpperCase(),{data,error}=await supabase.rpc('accept_peer_invite',{invite_code:code});if(error)return note(error.message);note('Maatje gekoppeld');q('#joinCode').value='';await loadPeers()};
async function loadPeers(){if(!configured)return;let user=await me();if(!user)return;let {data,error}=await supabase.rpc('my_peer_connections');if(error)return;q('#peerList').innerHTML=data?.length?data.map(x=>`<button class="peerButton" data-peer="${x.connection_id}" data-name="${escapeHtml(x.peer_name)}">♧ ${escapeHtml(x.peer_name)}</button>`).join(''):'<p class="fine">Nog geen gekoppelde maatjes.</p>'}
q('#peerList').onclick=e=>{let b=e.target.closest('[data-peer]');if(b)openChat(b.dataset.peer,b.dataset.name)};q('#closePeerChat').onclick=()=>{q('#peerChat').classList.add('hidden');channel?.unsubscribe()};
async function openChat(id,name){activePeer=id;q('#peerChat').classList.remove('hidden');q('#peerChatName').textContent=name;await messages();channel?.unsubscribe();channel=supabase.channel('peer-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'peer_messages',filter:'connection_id=eq.'+id},messages).subscribe()}
async function messages(){let {data}=await supabase.from('peer_messages').select('id,sender_id,body,created_at').eq('connection_id',activePeer).order('created_at');let user=await me();q('#peerMessages').innerHTML=(data||[]).map(x=>`<div class="peerMsg ${x.sender_id===user.id?'mine':''}">${escapeHtml(x.body)}<small>${new Date(x.created_at).toLocaleString('nl-NL')}</small></div>`).join('')}
q('#sendPeerMessage').onclick=async()=>{let body=q('#peerMessage').value.trim();if(!body||!activePeer)return;let user=await me(),{error}=await supabase.from('peer_messages').insert({connection_id:activePeer,sender_id:user.id,body});if(error)return note(error.message);q('#peerMessage').value=''};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();