(() => {
'use strict';
const $=s=>document.querySelector(s);
const ACCOUNT_PREFIX='serenamind.local.account.';
const ACTIVE_KEY='serenamind.local.active';
let selectedAvatar='';
const to64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
async function makeHash(password,salt){const p=new TextEncoder().encode(password);const data=new Uint8Array(salt.length+p.length);data.set(salt);data.set(p,salt.length);return to64(await crypto.subtle.digest('SHA-256',data))}

function readAvatar(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(!file.type.startsWith('image/'))return reject(new Error('type'));if(file.size>10*1024*1024)return reject(new Error('size'));const reader=new FileReader();reader.onerror=()=>reject(new Error('read'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('image'));img.onload=()=>{try{const max=360,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.78))}catch(e){reject(e)}};img.src=reader.result};reader.readAsDataURL(file)})}
function renderSelectedAvatar(data){selectedAvatar=data;const preview=$('#avatarPreview');if(preview)preview.src=data||fallbackAvatar($('#registerName')?.value||'S')}
async function chooseAvatar(input,statusId='#registerStatus'){const file=input?.files?.[0];if(!file)return;try{setMsg(statusId,'Foto wordt voorbereid...');const data=await readAvatar(file);renderSelectedAvatar(data);setMsg(statusId,'Profielfoto gekozen.',true)}catch(e){const text=e.message==='size'?'Kies een foto kleiner dan 10 MB.':e.message==='type'?'Kies een afbeeldingbestand.':'Deze foto kon niet worden gelezen. Kies een andere foto.';setMsg(statusId,text);input.value=''}}
async function updateCurrentAvatar(input){const file=input?.files?.[0],account=activeAccount();if(!file||!account)return;try{const data=await readAvatar(file);account.profile.avatar=data;localStorage.setItem(ACCOUNT_PREFIX+account.username,JSON.stringify(account));openApp(account);if($('#avatarPreview'))$('#avatarPreview').src=data}catch(e){alert(e.message==='size'?'Kies een foto kleiner dan 10 MB.':'Deze foto kon niet worden verwerkt.')}}

function setMsg(id,text,ok=false){const e=$(id);if(e){e.textContent=text;e.className='formStatus'+(ok?' ok':'')}}
function getAccount(username){try{return JSON.parse(localStorage.getItem(ACCOUNT_PREFIX+username)||'null')}catch{return null}}
function activeAccount(){const username=localStorage.getItem(ACTIVE_KEY);return username?getAccount(username):null}
function fallbackAvatar(name){const letter=(name?.[0]||'S').toUpperCase();return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect width="200" height="200" rx="55" fill="#eee9f8"/><circle cx="100" cy="72" r="38" fill="#7367a8"/><path d="M35 190c8-58 122-58 130 0" fill="#527f86"/><text x="100" y="193" text-anchor="middle" fill="white" font-size="20">${letter}</text></svg>`)}`}
function openApp(account){document.body.classList.add('authenticated');const auth=$('#authScreen');if(auth){auth.hidden=true;auth.style.display='none';auth.inert=true}const picture=account.profile.avatar||fallbackAvatar(account.profile.name);['#headerAvatar','#settingsAvatar'].forEach(id=>{const e=$(id);if(e)e.src=picture});const g=$('#greeting');if(g)g.textContent='Fijn dat je er bent, '+account.profile.name;const u=$('#profileUsername');if(u)u.textContent='@'+account.username;window.scrollTo(0,0)}
function openLogin(){document.body.classList.remove('authenticated');const auth=$('#authScreen');if(auth){auth.hidden=false;auth.style.display='flex';auth.inert=false}}
function switchTab(tab){$('#loginForm')?.classList.toggle('hidden',tab!=='login');$('#registerForm')?.classList.toggle('hidden',tab!=='register');document.querySelectorAll('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===tab))}
async function createAccount(){setMsg('#registerStatus','');const name=($('#registerName')?.value||'').trim();const username=($('#registerUser')?.value||'').trim().toLowerCase();const password=$('#registerPass')?.value||'';const repeat=$('#registerPass2')?.value||'';const role=$('#registerRole')?.value||'client';if(name.length<2)return setMsg('#registerStatus','Vul een naam of bijnaam in.');if(!/^[a-z0-9._-]{3,30}$/.test(username))return setMsg('#registerStatus','Gebruik 3 tot 30 kleine letters, cijfers, punt, streepje of underscore.');if(password.length<8)return setMsg('#registerStatus','Gebruik minimaal 8 tekens voor het wachtwoord.');if(password!==repeat)return setMsg('#registerStatus','De wachtwoorden zijn niet gelijk.');if(getAccount(username))return setMsg('#registerStatus','Deze gebruikersnaam bestaat al op dit apparaat.');const button=$('#registerBtn');button.disabled=true;button.textContent='Account maken...';try{const salt=crypto.getRandomValues(new Uint8Array(16));const hash=await makeHash(password,salt);const account={version:15,username,salt:to64(salt),hash,profile:{name,role,avatar:selectedAvatar||fallbackAvatar(name)},createdAt:new Date().toISOString()};localStorage.setItem(ACCOUNT_PREFIX+username,JSON.stringify(account));localStorage.setItem(ACTIVE_KEY,username);openApp(account)}catch(error){console.error(error);setMsg('#registerStatus','Account opslaan is mislukt. Gebruik SerenaMind buiten privemodus.');button.disabled=false;button.textContent='Account maken'}}
async function signIn(){setMsg('#loginSecurityMessage','');const username=($('#loginUser')?.value||'').trim().toLowerCase();const password=$('#loginPass')?.value||'';const account=getAccount(username);if(!account)return setMsg('#loginSecurityMessage','Account bestaat niet op dit apparaat.');try{const salt=Uint8Array.from(atob(account.salt),c=>c.charCodeAt(0));if(await makeHash(password,salt)!==account.hash)return setMsg('#loginSecurityMessage','Gebruikersnaam of wachtwoord klopt niet.');localStorage.setItem(ACTIVE_KEY,username);openApp(account)}catch(error){console.error(error);setMsg('#loginSecurityMessage','Inloggen is mislukt.')}}
function signOut(){localStorage.removeItem(ACTIVE_KEY);openLogin();switchTab('login')}
function install(){document.querySelectorAll('button').forEach(b=>b.type='button');const avatarInput=$('#avatarInput');if(avatarInput)avatarInput.addEventListener('change',()=>chooseAvatar(avatarInput));const changeInput=$('#changePhotoInput');if(changeInput)changeInput.addEventListener('change',()=>updateCurrentAvatar(changeInput));const changeButton=$('#changePhoto');if(changeButton)changeButton.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();changeInput?.click()},true);renderSelectedAvatar('');document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.matches('[data-auth]')){event.preventDefault();event.stopImmediatePropagation();switchTab(b.dataset.auth)}else if(b.id==='registerBtn'){event.preventDefault();event.stopImmediatePropagation();createAccount()}else if(b.id==='loginBtn'){event.preventDefault();event.stopImmediatePropagation();signIn()}else if(b.id==='logoutBtn'){event.preventDefault();event.stopImmediatePropagation();signOut()}},true);const a=activeAccount();a?openApp(a):openLogin()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('pageshow',()=>{const a=activeAccount();a?openApp(a):openLogin()});
})();